// Default modules data for Impact Trading Academy
// Auto-extracted from the original index.html

module.exports = [
  {
    id: 'm1',
    title: 'Mindset, Financial Reality & The Chasm of Fear',
    subtitle: 'Build the psychology and habits that separate the top 5% of traders from everyone else.',
    sections: [
      { title: 'Financial Reality Check', content: 'Many people never achieve their financial goals because they think and act like reactive, emotional retail traders. To measure your progress, reference Fidelity\'s age-based retirement benchmarks. These milestones provide a clear reality check on where you stand and where you need to be.', type: 'text' },
      { title: 'Fidelity Retirement Benchmarks', type: 'stats', stats: [
        { num: '1x', lbl: 'Salary by Age 30' },
        { num: '3x', lbl: 'Salary by Age 40' },
        { num: '6x', lbl: 'Salary by Age 50' },
        { num: '8x', lbl: 'Salary by Age 60' },
        { num: '10x', lbl: 'Salary by Age 67' }
      ]},
      { title: 'The Chasm of Fear', content: 'The ultimate determinant of success is mindset. 95% of people never reach the top 5% because attitudes, biases, beliefs, and fear hold them back. Crossing the "chasm of fear" requires three critical traits:\n\nFaith — Belief in your system and in yourself. Without faith, you\'ll second-guess every trade and abandon your plan at the worst moment.\n\nNo Fear — Achieved through strict risk management. When you know your downside is capped at 1%, fear loses its grip.\n\nCourage — Taking bold, decisive steps toward your goals. Courage isn\'t the absence of fear — it\'s acting despite it.', type: 'text' },
      { title: 'The Five Pillars of Success', content: 'Every successful trader follows these five pillars:\n\n1. Stack the odds in your favor — Use strategies backed by data and history, not gut feelings.\n2. Follow rules — Rules protect you from emotional mistakes that destroy accounts.\n3. Be disciplined — Consistency beats intensity every single time.\n4. Be coachable — Learn from others with proven results and be willing to adapt.\n5. Be decisive — Success requires taking action, not endless analysis paralysis.', type: 'text' },
      { title: 'The Structural Advantage of Starting Small', content: '"It is a huge structural advantage to not have a lot of money." Smaller accounts offer more agility — you can enter and exit positions quicker and pursue high-growth opportunities that large funds cannot.\n\nThe S&P 500 returns ~10% annually long-term. Berkshire Hathaway compounds at ~20%. The difference? Over 30 years, $10,000 at 10% becomes $174,000. At 20%, it becomes $2.37 million. Even a small increase in your annual compounding rate creates a massive long-term difference.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'learn', title: 'Fidelity: Average Retirement Savings by Age', desc: 'Official benchmarks showing retirement savings goals with interactive calculators.', url: 'https://www.fidelity.com/learning-center/personal-finance/average-retirement-savings' },
        { icon: 'chart', title: 'Schwab: Benefits of Compound Growth', desc: 'Interactive compound interest calculator showing exponential growth over time.', url: 'https://www.schwabmoneywise.com/essentials/benefits-of-compound-growth' },
        { icon: 'tool', title: 'Investor.gov: Compound Interest Calculator', desc: 'Free government tool to calculate how compounding affects your investments.', url: 'https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator' }
      ]}
    ],
    quiz: [
      { question: 'According to Fidelity benchmarks, how much should you have saved by age 67?', options: ['5x annual salary', '8x annual salary', '10x annual salary', '15x annual salary'], correct: 2, explanation: 'Fidelity recommends having 10x your annual salary saved by age 67.' },
      { question: 'What are the three traits needed to cross the "Chasm of Fear"?', options: ['Speed, Power, Intelligence', 'Faith, No Fear, Courage', 'Patience, Logic, Timing', 'Knowledge, Capital, Luck'], correct: 1, explanation: 'The three traits are Faith (in your system), No Fear (through risk management), and Courage (bold action).' },
      { question: 'Which is NOT one of the Five Pillars of successful trading?', options: ['Stack the odds in your favor', 'Be disciplined', 'Trust your gut instinct', 'Be coachable'], correct: 2, explanation: 'The five pillars are: stack odds, follow rules, be disciplined, be coachable, and be decisive. Trusting gut instinct is emotional, not systematic.' },
      { question: 'Why is starting with a small account considered a structural advantage?', options: ['Lower taxes on gains', 'More agility to enter/exit positions quickly', 'Brokers give better commission rates', 'Less regulatory paperwork required'], correct: 1, explanation: 'Smaller accounts provide agility — you can enter and exit positions quicker and pursue high-growth opportunities that large funds cannot.' }
    ]
  },
  {
    id: 'm2',
    title: 'Market Mechanics, Supply & Demand, and Chart Reading',
    subtitle: 'Understand how institutional money moves markets and learn to read price action like a professional.',
    sections: [
      { title: 'Who Really Moves the Market?', content: 'Total market capitalization is approximately $50 trillion. Institutional investors account for 80–90% of all market volume, while retail traders only account for 10–20%. This is the single most important fact to internalize: institutions control the market. Your job is to follow their "footprints in the sand" — a concept from legendary investor Peter Lynch — to study what big money is quietly accumulating.', type: 'text' },
      { title: 'Market Volume Breakdown', type: 'stats', stats: [
        { num: '80-90%', lbl: 'Institutional Volume' },
        { num: '10-20%', lbl: 'Retail Volume' },
        { num: '$50T', lbl: 'Total Market Cap' }
      ]},
      { title: 'Supply & Demand: The #1 Law of Markets', content: 'The single most important law governing all markets:\n\nLow Supply → Price Goes Up\nHigh Supply → Price Goes Down\n\nThis fundamental principle creates demand zones and supply zones on the chart. When massive institutional orders are not fully executed, they leave behind "unfilled orders" that create fundamental market imbalances. These imbalances are the footprints you\'re looking for.', type: 'text' },
      { title: 'Reading the Price Bar (OHLC)', content: 'An Open-High-Low-Close bar tells you four critical pieces of information:\n\nOpen — Where the price started the session\nHigh — The highest price reached during the session\nLow — The lowest price dropped during the session\nClose — The final price when the session ended\n\nThis is the foundation of all chart reading. Every influence — news, earnings, Fed announcements, fear, greed — gets reflected in these four data points. Market Hours (Louisiana/CST): Opens 8:30 AM, Closes 3:00 PM.', type: 'text' },
      { title: 'Demand Zones & Supply Zones', content: 'Demand Zones are created by leftover institutional buy orders. In long trading, you trade inside demand zones to buy low and sell high:\n• Step 1: Buy to Enter\n• Step 2: Sell to Exit\n• Profit when: Price rises\n\nSupply Zones are created by leftover institutional sell orders. In short trading, you trade inside supply zones to sell high and buy low:\n• Step 1: Sell to Enter\n• Step 2: Buy to Exit\n• Profit when: Price falls', type: 'text' },
      { title: 'How Orders Create Movement', content: 'When a buyer wants 100 shares of ABC at $41.30 and supply equals demand, price stays balanced. When no more shares are available at that price, an imbalance occurs and price must move.\n\nBalance → Imbalance → Movement\n\nThis is the key to understanding all price action. Unfilled orders are leftover pockets of institutional buying or selling pressure that were never executed. They create predictable zones where price is likely to react in the future.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'chart', title: 'CME Group: Chart Types — Candlestick, Line, Bar', desc: 'Official CME course explaining OHLC charts and how to read each component.', url: 'https://www.cmegroup.com/education/courses/technical-analysis/chart-types-candlestick-line-bar' },
        { icon: 'learn', title: 'TrendSpider: Supply and Demand Zones Explained', desc: 'Detailed guide with chart examples showing how to identify supply and demand zones.', url: 'https://trendspider.com/learning-center/what-are-supply-and-demand-zones/' },
        { icon: 'chart', title: 'TradingView: Institutional vs Retail Activity Indicator', desc: 'Live indicator showing institutional volume surges vs retail trading activity.', url: 'https://www.tradingview.com/script/6LT81C3T-Enhanced-Retail-vs-Institutional-Activity/' },
        { icon: 'learn', title: 'Market Bulls: Institutional vs Retail Traders Comparison', desc: 'Deep comparison of how institutional and retail traders approach the market.', url: 'https://market-bulls.com/institutional-traders-vs-retail-traders/' }
      ]}
    ],
    quiz: [
      { question: 'What percentage of market volume do institutional investors control?', options: ['50–60%', '60–70%', '80–90%', '95–99%'], correct: 2, explanation: 'Institutional investors account for 80–90% of all market volume.' },
      { question: 'What does a Demand Zone represent?', options: ['Area of heavy selling pressure', 'Leftover institutional buy orders', 'Where retail traders congregate', 'Government price controls'], correct: 1, explanation: 'Demand zones are created by leftover institutional buy orders that were never fully executed.' },
      { question: 'In a long trade, what is the first execution step?', options: ['Sell to Enter', 'Buy to Enter', 'Set Stop Loss', 'Check Volume'], correct: 1, explanation: 'In long trading (buy low, sell high), the first step is Buy to Enter, then Sell to Exit.' },
      { question: 'What creates price movement according to order flow theory?', options: ['News announcements only', 'Balance → Imbalance → Movement', 'Random walk patterns', 'Technical indicator crossovers'], correct: 1, explanation: 'When supply and demand become imbalanced due to unfilled orders, price must move to find new equilibrium.' }
    ]
  },
  {
    id: 'm3',
    title: 'The Master Surge Strategy: Five Pillars of Institutional Timing',
    subtitle: 'Your primary timing mechanism to identify market turns and major moves in advance.',
    sections: [
      { title: 'Strategy Overview', content: 'The Master Surge Strategy functions as your primary timing mechanism, designed to help you identify market turns and major moves before they happen. Its core principle: follow the "footprints in the sand" to track what massive institutional money is quietly accumulating.\n\nTo stack the odds in your favor, you must combine all five pillars together. No single pillar works in isolation — the power comes from confirmation across multiple signals.', type: 'text' },
      { title: 'The Five Pillars', type: 'stats', stats: [
        { num: '1', lbl: 'Price Cycles' },
        { num: '2', lbl: 'Volume Surges' },
        { num: '3', lbl: 'Inst. Footprints' },
        { num: '4', lbl: 'Trend Strength' },
        { num: '5', lbl: 'Risk Management' }
      ]},
      { title: 'Pillar 1: Understand Price Cycles', content: 'Markets move in four repeating phases: Accumulation (institutions quietly buying), Markup (price rising as demand overwhelms supply), Distribution (institutions quietly selling into strength), and Markdown (price falling as supply overwhelms demand).\n\nRecognizing which phase the market is in helps you time entries with precision rather than guessing.', type: 'text' },
      { title: 'Pillar 2: Track Volume Surges', content: 'Since institutions control 80–90% of market volume, unusual volume spikes are direct evidence of big money entering or exiting positions. A volume surge that accompanies a price move confirms the move is backed by institutional conviction, not just retail noise.', type: 'text' },
      { title: 'Pillar 3: Watch Institutional Footprints', content: 'Identify "unfilled orders" on your chart — the leftover pockets of massive institutional buying or selling pressure that were never fully executed. These create predictable supply and demand zones where price is highly likely to react when revisited.', type: 'text' },
      { title: 'Pillar 4: Confirm Trend Strength', content: 'Always ensure the overarching market trend supports your intended trade direction. Trading with the trend means you have institutional momentum on your side. Trading against the trend means fighting the biggest players in the market.', type: 'text' },
      { title: 'Pillar 5: Use Risk Management Every Time', content: 'Strictly limit risk to a maximum of 1% per trade. Aim for a 3:1 reward-to-risk ratio using the S.E.T. rule (Stop, Entry, Target). This mathematical edge means even with only a 30% win rate, you remain consistently profitable over time.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'chart', title: 'Schwab: Four Stages of the Stock Market Cycle', desc: 'Learn to identify Accumulation, Markup, Distribution, and Markdown phases.', url: 'https://www.schwab.com/learn/story/four-stages-stock-market-cycles' },
        { icon: 'learn', title: 'Visual Capitalist: Market Cycle Diagram', desc: 'Infographic showing the best time to buy stocks within market cycles.', url: 'https://www.visualcapitalist.com/this-market-cycle-diagram-explains-the-best-time-to-buy-stocks/' },
        { icon: 'chart', title: 'TradingView: Volume Surge Detector', desc: 'Indicator that highlights institutional volume spikes using color-coded alerts.', url: 'https://www.tradingview.com/script/RY2Dda1o/' }
      ]}
    ],
    quiz: [
      { question: 'What is the primary purpose of the Master Surge Strategy?', options: ['Scalping small profits quickly', 'Identifying market turns and major moves in advance', 'Automated algorithmic trading', 'Long-term buy and hold investing'], correct: 1, explanation: 'The Master Surge Strategy is your primary timing mechanism to identify market turns and major moves before they happen.' },
      { question: 'What are the four phases of a market cycle?', options: ['Buy, Hold, Sell, Wait', 'Accumulation, Markup, Distribution, Markdown', 'Opening, Trending, Consolidation, Closing', 'Fear, Greed, Panic, Recovery'], correct: 1, explanation: 'Markets cycle through Accumulation, Markup, Distribution, and Markdown phases.' },
      { question: 'Why is tracking volume surges important?', options: ['It predicts exact price targets', 'It confirms institutional activity', 'It replaces the need for risk management', 'It eliminates all trading losses'], correct: 1, explanation: 'Volume surges confirm institutional activity since institutions control 80–90% of market volume.' }
    ]
  },
  {
    id: 'm4',
    title: 'Risk Management and the S.E.T. Rule',
    subtitle: 'The foundation of all profitable trading: control your downside on every single trade.',
    sections: [
      { title: 'Why Risk Management is Everything', content: 'A 70% losing percentage is considered terrible by most people. But with proper risk management, a 70% loss rate can still be profitable. The goal is never perfection — it\'s profitability through mathematical edge and risk control. This is what separates professionals from amateurs.', type: 'text' },
      { title: 'The 1% Rule', content: 'Never risk more than 1% of your total trading portfolio per trade. This is non-negotiable.\n\nCalculation: Total Account Balance × 1% = Maximum Dollar Risk Per Trade\n\nExample: $10,000 account × 1% = $100 max risk per trade\nExample: $50,000 account × 1% = $500 max risk per trade\n\nThis ensures no single trade can significantly damage your account, allowing you to survive losing streaks and stay in the game.', type: 'text' },
      { title: 'The 3:1 Reward-to-Risk Ratio', content: 'For every $1 you risk, aim to earn $3. This creates a powerful mathematical advantage:\n\nRisk per trade = 1% of account\nReward target = 3% of account\n\nEven winning only 30% of trades:\n(30 wins × $3) – (70 losses × $1) = $90 – $70 = $20 net profit per 100 trades\n\nThis is how traders survive downturns and grow consistently over time.', type: 'text' },
      { title: 'Profitability at Different Win Rates (3:1 Ratio)', type: 'table', headers: ['Win Rate', 'Wins (per 100)', 'Gain', 'Loss', 'Net Result'], rows: [
        ['25%', '25', '+$75', '-$75', 'Break Even'],
        ['30%', '30', '+$90', '-$70', '+$20 Profit'],
        ['40%', '40', '+$120', '-$60', '+$60 Profit'],
        ['50%', '50', '+$150', '-$50', '+$100 Profit'],
        ['60%', '60', '+$180', '-$40', '+$140 Profit']
      ]},
      { title: 'The S.E.T. Rule', content: 'Every trade must have a S.E.T. defined before you ever press the button:\n\nS — Stop: Your protective floor (for longs) or ceiling (for shorts). This caps your downside at exactly 1% of your account. Set it and never move it against your position.\n\nE — Entry: Your exact buy or sell trigger. This must be prepared before the price move happens, not during it. Chasing price is a losing strategy.\n\nT — Target: Your 3% profit objective (3:1 ratio). When price hits your target, you take profit. No hoping, no greed, no "maybe it\'ll go higher."\n\nThis creates consistency, discipline, and controlled risk on every single trade.', type: 'text' },
      { title: 'Position Sizing Formula', content: 'Position Size = Account Risk ÷ Trade Risk\n\nAccount Risk = 1% of total account value (your max dollar risk)\nTrade Risk = Distance between Entry and Stop in dollar terms\n\nExample: $50,000 account, Entry at $100, Stop at $98\nAccount Risk = $50,000 × 1% = $500\nTrade Risk = $100 – $98 = $2 per share\nPosition Size = $500 ÷ $2 = 250 shares\n\nNote: Always verify position sizing calculations independently before trading.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'learn', title: 'FOREX.com: Risk vs Reward Explained', desc: 'Visual guide to understanding and applying risk-reward ratios in real trades.', url: 'https://www.forex.com/en-us/trading-academy/courses/successful-trading-techniques/risk-vs-reward/' },
        { icon: 'chart', title: 'StockGro: Stop Loss and Target in Trading', desc: 'Visual walkthrough of setting Stop, Entry, and Target points on live charts.', url: 'https://www.stockgro.club/blogs/trading/stop-loss-and-target-in-trading/' },
        { icon: 'tool', title: 'TradesViz: Stop Loss & Profit Target Simulator', desc: 'Interactive simulator to practice setting stops and targets before real trading.', url: 'https://www.tradesviz.com/blog/stop-loss-profit-target-trade-simulator/' }
      ]}
    ],
    quiz: [
      { question: 'What is the maximum percentage of your portfolio you should risk per trade?', options: ['5%', '3%', '2%', '1%'], correct: 3, explanation: 'Never risk more than 1% of your total trading portfolio per trade.' },
      { question: 'What does S.E.T. stand for?', options: ['Signal, Execute, Track', 'Stop, Entry, Target', 'Strategy, Emotion, Timing', 'Supply, Entry, Trend'], correct: 1, explanation: 'S.E.T. = Stop (protective floor/ceiling), Entry (buy/sell trigger), Target (profit objective at 3:1).' },
      { question: 'With a 3:1 ratio, what win rate is needed to break even?', options: ['50%', '25%', '33%', '10%'], correct: 1, explanation: 'At 3:1 ratio, you need ~25% wins to break even: (25 × $3) = $75 gain vs (75 × $1) = $75 loss.' },
      { question: 'If your account is $20,000, what is your maximum risk per trade?', options: ['$100', '$200', '$500', '$600'], correct: 1, explanation: '$20,000 × 1% = $200 maximum risk per trade.' }
    ]
  },
  {
    id: 'm5',
    title: 'Leverage Strategy and Asset Vehicles',
    subtitle: 'Choose the right investment vehicle for your goals, timeframe, and account size.',
    sections: [
      { title: 'Good Leverage vs. Bad Leverage', content: 'Leverage is the most misunderstood concept in trading. There are only two kinds:\n\nGood Leverage — Used on non-depreciating assets, backed by strategy and strict risk management, enhances returns without risking ruin.\n\nBad Leverage — Emotional, speculative, used on depreciating assets with no risk control. This is how accounts get destroyed overnight.\n\nThe difference is never the amount of leverage — it\'s whether you have a plan and the discipline to follow it.', type: 'text' },
      { title: 'Mutual Funds vs. ETFs', type: 'table', headers: ['Feature', 'Mutual Funds', 'ETFs'], rows: [
        ['Trading', 'Once/day at market close', 'Throughout the day like stocks'],
        ['Fees', 'Higher fees & commissions', 'Lower fees, low/no commissions'],
        ['Leverage', 'No leverage available', 'Leverage available'],
        ['Short Selling', 'Cannot short sell', 'Can trade long and short'],
        ['Stop-Loss Orders', 'Cannot set stop-loss', 'Stop-loss orders permitted'],
        ['Market Conditions', 'Primarily for bull markets', 'Work in bull and bear markets'],
        ['Options', 'Not compatible with options', 'Compatible with options strategies']
      ]},
      { title: 'Options & LEAPS (10x–20x Leverage)', content: 'Options give you the right to control 100 shares of a stock for a fraction of the total cost (the premium). Your maximum possible loss is strictly capped at the premium you paid — making options perfect for the 1% risk rule.\n\nKey terms: Strike Price (the price to buy/sell the stock), Expiration Date (when the option expires, ranging from 1 day to 3 years).\n\nLEAPS (Long-Term Equity Anticipation Securities) are options expiring 2–3 years out, giving trades plenty of time to develop. Options are ideal for weekly and monthly income.', type: 'text' },
      { title: 'Futures & S&P 500 Micro E-mini (20x–200x Leverage)', content: 'Futures provide massive leverage and 23-hour daily market access, significantly reducing overnight gap risk. The MES contract is 1/10th the size of the standard S&P 500 contract.\n\nKey advantages:\n• No $25,000 pattern day-trading requirement (only $2,000 needed)\n• 60/40 tax rule: 60% of gains taxed at long-term rate\n• Low commissions and exchange fees\n• 23-hour electronic trading access\n\nCritical warning: Because risk is not naturally capped like options, futures require professional-level risk management and strict use of stop orders.', type: 'text' },
      { title: 'Income Strategy by Timeframe', type: 'table', headers: ['Timeframe', 'Vehicle', 'Min. Account', 'Leverage'], rows: [
        ['Daily', 'Futures', '$2,000', '20x–200x'],
        ['Weekly', 'Options & Futures', '$5,000', '10x–200x'],
        ['Monthly', 'Options & Forex/Crypto', '$25,000', '10x–100x'],
        ['Quarterly', 'Options & Forex/Crypto', '$50,000', '10x–100x'],
        ['Yearly/Wealth', 'Stocks', '$250,000', 'None'],
        ['ETFs/Bonds', 'ETFs', '$50,000', 'Available']
      ]},
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'learn', title: 'Vanguard: ETFs vs Mutual Funds — Which to Choose', desc: 'Official side-by-side comparison with fee analysis and use cases.', url: 'https://investor.vanguard.com/investor-resources-education/etfs/etf-vs-mutual-fund' },
        { icon: 'learn', title: 'Fidelity: Mutual Fund or ETF?', desc: 'Interactive tool to help decide which vehicle fits your strategy.', url: 'https://www.fidelity.com/viewpoints/investing-ideas/mutual-fund-or-etf' },
        { icon: 'chart', title: 'OANDA: Beginner\'s Guide to Leverage Trading', desc: 'Explains good vs bad leverage with real examples and risk scenarios.', url: 'https://www.oanda.com/us-en/learn/introduction-to-leverage-trading/what-is-leverage-trading/' }
      ]}
    ],
    quiz: [
      { question: 'What leverage range do Futures offer?', options: ['5x–10x', '10x–20x', '20x–200x', '500x–1000x'], correct: 2, explanation: 'Futures provide 20x to 200x leverage, requiring professional-level risk management.' },
      { question: 'What is the minimum recommended account for daily futures trading?', options: ['$500', '$2,000', '$10,000', '$25,000'], correct: 1, explanation: 'Futures avoid the $25,000 pattern day-trading requirement, needing only $2,000.' },
      { question: 'What makes options inherently safer than futures in terms of risk?', options: ['Lower leverage', 'Government insurance', 'Max loss capped at premium paid', 'Guaranteed profits'], correct: 2, explanation: 'With options, your maximum loss is strictly capped at the premium you paid.' },
      { question: 'What is the 60/40 tax rule for futures?', options: ['60% tax, 40% keep', '60% long-term rate, 40% short-term rate', '60% deductible, 40% taxable', '60% federal, 40% state'], correct: 1, explanation: '60% of futures gains are taxed at the favorable long-term rate, 40% at short-term rate.' }
    ]
  },
  {
    id: 'm6',
    title: 'Options Deep Dive: Mechanics, LEAPS & Strategy',
    subtitle: 'Master the complete mechanics of options trading — from premiums to strike prices to expiration.',
    sections: [
      { title: 'What Is an Options Trade?', content: 'Options give you the right, but not the obligation, to buy or sell a stock at a certain price by a certain date. The most you can ever lose is the premium you paid. Example: Pay $500 for a call option → your absolute maximum loss is $500, no matter how badly the trade goes.', type: 'text' },
      { title: 'How Options Are Quoted', content: 'Options are quoted per share but control 100 shares per contract:\n\nQuoted price: $5.00 per share\nActual cost: $5.00 × 100 shares = $500 total\n\nThis is critical to understand for proper position sizing and risk calculation.', type: 'text' },
      { title: '100 Shares vs. 1 Call Option', type: 'table', headers: ['Method', 'What You Control', 'Cost', 'Max Loss'], rows: [
        ['Buy 100 Shares', '100 shares directly', '$10,000', '$10,000 (full amount)'],
        ['Buy 1 Call Option', 'Right to 100 shares', '$500 (premium)', '$500 (premium only)']
      ]},
      { title: 'Strike Price & Expiration', content: 'Every option has two defining characteristics:\n\nStrike Price — The price at which you can buy the stock (for a call) or sell the stock (for a put). This is your target execution price.\n\nExpiration Date — The last day the option is valid. Options can expire anywhere from 1 day to 3 years (LEAPS). You always choose both before you buy.', type: 'text' },
      { title: 'LEAPS: Long-Term Options', content: 'LEAPS (Long-Term Equity Anticipation Securities) are simply long-term options that expire up to 2–3 years in the future. They behave exactly like regular options but give your trades substantially more time to develop.\n\nAdvantages of LEAPS:\n• More time for the stock to make the move you want\n• Less time decay pressure than short-term options\n• Can be used for swing trading or position trading\n• Ideal for capturing large multi-month moves', type: 'text' },
      { title: 'Complete Example Trade', content: 'Scenario:\n• Stock price: $100\n• Strike price: $90 (call option)\n• Premium: $5.00 per share = $500 total\n• You control: $9,000 worth of stock (100 shares × $90)\n\nOutcome if stock rises to $110:\nOption value increases significantly. Your $500 investment controls $9,000 worth of stock.\n\nOutcome if stock drops to $80:\nYour maximum loss is $500 (the premium). Not $9,000. Not $10,000. Just $500.\n\nThis is the power of defined-risk leverage.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'learn', title: 'CME Group: Understanding Options Expiration & P/L', desc: 'Official course covering strike prices, premiums, and payoff diagrams.', url: 'https://www.cmegroup.com/education/courses/introduction-to-options/understanding-options-expiration-profit-and-loss' },
        { icon: 'learn', title: 'Options Industry Council: How LEAPS Work', desc: 'Official guide to LEAPS with payoff comparisons to short-term options.', url: 'https://www.optionseducation.org/optionsoverview/how-leaps-work' },
        { icon: 'chart', title: 'Fidelity: LEAPS and Bounds', desc: 'Practical strategies for using LEAPS in your portfolio.', url: 'https://www.fidelity.com/viewpoints/active-investor/leaps-and-bounds' },
        { icon: 'learn', title: 'SoFi: Strike Price Explained', desc: 'Visual breakdown of how strike prices work with real-world examples.', url: 'https://www.sofi.com/learn/content/strike-price-options-trading/' }
      ]}
    ],
    quiz: [
      { question: 'How many shares does 1 options contract control?', options: ['10 shares', '50 shares', '100 shares', '1,000 shares'], correct: 2, explanation: 'One options contract controls 100 shares of the underlying stock.' },
      { question: 'If an option is quoted at $3.50, what is the total cost?', options: ['$3.50', '$35', '$350', '$3,500'], correct: 2, explanation: '$3.50 per share × 100 shares per contract = $350 total cost.' },
      { question: 'What is the maximum you can lose on a purchased option?', options: ['Unlimited', 'The premium paid', '50% of premium', 'The strike price'], correct: 1, explanation: 'The maximum loss on a purchased option is strictly capped at the premium you paid.' },
      { question: 'How long can LEAPS options last?', options: ['1 month max', '6 months', 'Up to 2–3 years', 'Forever'], correct: 2, explanation: 'LEAPS are long-term options that can expire up to 2–3 years in the future.' }
    ]
  },
  {
    id: 'm7',
    title: 'Futures Trading: The 23-Hour Advantage',
    subtitle: 'Master the unique benefits of futures — from tax advantages to around-the-clock market access.',
    sections: [
      { title: 'Why 23-Hour Access Matters', content: 'Futures markets (including the S&P 500 Micro E-mini) are open nearly around the clock, providing 23-hour electronic trading access. This extended schedule offers two critical advantages:\n\n1. Flexible Income Generation — Daily income typically requires only 1–2 hours of active trading\n2. Reduced Overnight Risk — Because the market is almost continuously open, overnight price gaps are significantly reduced compared to stock trading', type: 'text' },
      { title: 'S&P 500 Micro E-mini (MES) Key Facts', type: 'stats', stats: [
        { num: '1/10', lbl: 'Size of Standard ES' },
        { num: '$2K', lbl: 'Min. Account' },
        { num: '23hr', lbl: 'Daily Access' },
        { num: '60/40', lbl: 'Tax Advantage' }
      ]},
      { title: 'Complete Futures Advantages', content: '• No $25,000 Day-Trading Minimum — Unlike stocks, you don\'t need $25K to day trade. Only ~$2,000 recommended.\n• High Leverage (20x–200x) — Capture large market moves with small capital.\n• 23-Hour Trading — Trade when it fits your schedule, not just market hours.\n• Reduced Gap Risk — Near-continuous trading means fewer surprise gaps.\n• 60/40 Tax Treatment — 60% of gains taxed at favorable long-term rate.\n• Low Commissions — Cost-efficient execution.\n• Daily & Weekly Income — Designed for active income generation.', type: 'text' },
      { title: 'The 60/40 Tax Rule Explained', content: 'Under Section 1256 of the tax code, futures qualify for special treatment:\n\n60% of gains → Taxed at long-term capital gains rate (lower)\n40% of gains → Taxed at short-term capital gains rate (higher)\n\nThis applies regardless of how long you hold the position. A day trade in futures still gets 60/40 treatment. This structural advantage means futures traders keep significantly more of their profits compared to stock day traders who pay 100% short-term rates.', type: 'text' },
      { title: 'Major Futures Market Categories', type: 'table', headers: ['Category', 'Examples'], rows: [
        ['Equity Index', 'S&P 500, Nasdaq, Dow, Russell, DAX, Nikkei'],
        ['Interest Rates', '10-Year Treasury, 30-Year Bond, 2-Year Note'],
        ['Energy & Metals', 'Crude Oil, Natural Gas, Gold, Silver, Copper'],
        ['Currencies', 'Euro, Yen, Swiss Franc, GBP, AUD, CAD, USD Index'],
        ['Agriculture/Softs', 'Corn, Soybeans, Wheat, Coffee, Cocoa, Cotton, Sugar']
      ]},
      { title: 'Critical Risk Warning', content: 'While leverage and 23-hour access are major benefits, futures require the highest level of discipline and risk management of any vehicle covered in this training.\n\nUnlike options where your risk is capped at the premium paid, futures losses can exceed your initial investment. You MUST:\n• Use protective stop orders on every single trade\n• Never risk more than 1% of your account\n• Apply the S.E.T. rule without exception\n• Never trade futures without a written plan', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'learn', title: 'CME Group: Micro E-mini S&P 500 Contract Specs', desc: 'Official MES contract details including margin, tick size, and trading hours.', url: 'https://www.cmegroup.com/markets/equities/sp/micro-e-mini-sandp-500.html' },
        { icon: 'learn', title: 'Schwab: What is a Micro E-Mini Future?', desc: 'Beginner-friendly explanation of micro futures with real examples.', url: 'https://www.schwab.com/learn/story/what-is-micro-e-mini-future' },
        { icon: 'chart', title: 'High Strike: Futures 60/40 Tax Rule Guide', desc: 'Detailed breakdown of Section 1256 tax treatment with examples.', url: 'https://highstrike.com/futures-60-40-tax-rule/' },
        { icon: 'learn', title: 'Schwab: Trader Taxes & Section 1256 Contracts', desc: 'How to report futures taxes and maximize the 60/40 advantage.', url: 'https://www.schwab.com/learn/story/trader-taxes-form-8949-section-1256-contracts' }
      ]}
    ],
    quiz: [
      { question: 'How many hours per day can you trade futures?', options: ['8 hours', '12 hours', '23 hours', '24 hours'], correct: 2, explanation: 'Futures provide 23-hour daily electronic trading access.' },
      { question: 'What is the MES contract?', options: ['Full-size S&P 500 futures', '1/10th size of standard S&P 500 contract', 'A type of option', 'A mutual fund'], correct: 1, explanation: 'MES is the Micro E-mini S&P 500 futures contract, 1/10th the size of the regular ES contract.' },
      { question: 'Under the 60/40 rule, what percentage is taxed at long-term rates?', options: ['40%', '50%', '60%', '100%'], correct: 2, explanation: '60% of futures gains are taxed at the favorable long-term capital gains rate.' },
      { question: 'What minimum account is needed for daily futures trading?', options: ['$500', '$2,000', '$10,000', '$25,000'], correct: 1, explanation: 'Futures require only ~$2,000 for daily income trading, avoiding the $25,000 PDT rule.' }
    ]
  },
  {
    id: 'm8',
    title: 'Practical Trade Execution: Scanning Zones & Entering Positions',
    subtitle: 'Bridge the gap from theory to action — the step-by-step workflow for finding institutional zones and executing trades.',
    sections: [
      { title: 'From Theory to Execution', content: 'Modules 2, 3, and 4 taught you what supply/demand zones are, how the Master Surge Strategy works, and why risk management matters. This module answers the most critical question: how do you actually find these zones on a live chart and execute a trade?\n\nThe answer is a four-step workflow: Scan, Spot, Anticipate, Execute. Every trade you take should follow this sequence. No shortcuts, no skipping steps.', type: 'text' },
      { title: 'The 4-Step Execution Workflow', type: 'stats', stats: [
        { num: '1', lbl: 'Scan' },
        { num: '2', lbl: 'Spot' },
        { num: '3', lbl: 'Anticipate' },
        { num: '4', lbl: 'Execute' }
      ]},
      { title: 'Step 1: Scan for Past Imbalance Areas', content: 'Open your price chart and scan for established areas where the market previously lost balance and price moved significantly. You are looking for two things:\n\nFor Long Entries — Find areas where price moved sharply upward. These upward moves were caused by unfilled institutional buy orders creating demand zones below.\n\nFor Short Entries — Find areas where price moved sharply downward. These downward moves were caused by unfilled institutional sell orders creating supply zones above.\n\nThe sharper the move, the stronger the imbalance. A slow, grinding move suggests balanced trading. A fast, aggressive move suggests a massive institutional order that left unfilled orders behind.', type: 'text' },
      { title: 'Step 2: Spot the Institutional Footprints', content: 'Within those past imbalance areas, look for evidence that leftover institutional orders are still waiting to be filled. The key evidence is price behavior when it revisits the zone:\n\nStrong Footprint Signals:\n— Price previously left the area rapidly (fast departure = large unfilled orders)\n— The zone has not been revisited yet (fresh zones are stronger than tested zones)\n— Multiple timeframes confirm the same zone (daily + 4-hour alignment)\n\nWeak Footprint Signals:\n— Price drifted slowly out of the area (suggests orders were mostly filled)\n— The zone has been tested multiple times (each test fills more orders, weakening the zone)\n— Only visible on a single low timeframe', type: 'text' },
      { title: 'Step 3: Anticipate — Plan Before Price Arrives', content: 'This is where most retail traders fail. They wait for the price to start moving and then scramble to react. Professionals do the opposite — they plan everything before price arrives at their zone.\n\nBefore price reaches your identified zone, you must define your complete S.E.T.:\n\nStop — Set your protective floor (for longs) or ceiling (for shorts) just beyond the zone boundary. This caps your risk at exactly 1%.\n\nEntry — Your exact trigger price within the zone. This is where you will enter if price reaches it. No chasing.\n\nTarget — Your 3:1 profit objective. Calculate this from your Entry, not from where price currently is.\n\nWrite these three numbers down or set them in your platform before the trade happens. If price never reaches your zone, you simply do not trade. Patience is a strategy.', type: 'text' },
      { title: 'Step 4: Execute the Trade', content: 'When price arrives at your predetermined zone and hits your Entry trigger:\n\nLong Trade Execution (in Demand Zones):\n— Step A: Buy to Enter at your predefined Entry price\n— Step B: Stop loss is already set (protecting your 1% max risk)\n— Step C: Sell to Exit when price hits your Target (3:1 ratio)\n— You profit when price rises from the demand zone\n\nShort Trade Execution (in Supply Zones):\n— Step A: Sell to Enter at your predefined Entry price\n— Step B: Stop loss is already set (protecting your 1% max risk)\n— Step C: Buy to Exit when price hits your Target (3:1 ratio)\n— You profit when price falls from the supply zone\n\nCritical rule: If the zone breaks (price blows through your Stop), accept the 1% loss and move on. Never move your Stop further away to "give it more room." That is how accounts get destroyed.', type: 'text' },
      { title: 'Price Action Over Indicators', content: 'A common mistake new traders make is loading their charts with technical indicators — moving averages, RSI, MACD, Bollinger Bands — and using them as primary decision tools. The institutional approach taught in this academy is fundamentally different.\n\nEvery influence on a stock\'s price — news, earnings, Fed announcements, fear, greed — is already reflected in the OHLC (Open, High, Low, Close) price bars on your chart. The price bar IS the final verdict of all market forces combined.\n\nTechnical indicators should only be used as a secondary backup, never as your primary reason to enter a trade. Your primary tools are:\n\n1. Supply and demand zones (institutional footprints)\n2. Price action at those zones (how price behaves when it arrives)\n3. The S.E.T. rule (your execution framework)\n\nIf you focus on reading the price action and the institutional imbalances, you are reading what the market is actually doing — not what a lagging indicator says it might be doing.', type: 'text' },
      { title: 'Confirming Trend Direction with Supply & Demand', content: 'Pillar 4 of the Master Surge Strategy says to confirm trend strength before trading. But how?\n\nRather than relying on trend-following indicators, confirm the trend by reading the institutional supply and demand structure:\n\nUptrend Confirmation:\n— Price is making higher demand zones (each bounce starts from a higher level)\n— Supply zones are being broken and absorbed (institutions buying through resistance)\n— Fresh demand zones below current price remain untested\n\nDowntrend Confirmation:\n— Price is making lower supply zones (each rejection starts from a lower level)\n— Demand zones are being broken and absorbed (institutions selling through support)\n— Fresh supply zones above current price remain untested\n\nThe core principle: a strong upward trend means low supply is driving prices up, and a strong downward trend means high supply is driving prices down. When the supply/demand structure aligns with your intended trade direction, you have institutional momentum on your side.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'chart', title: 'TradingView: Supply & Demand Zone Drawing Tools', desc: 'Practice identifying and marking supply/demand zones on live charts with free tools.', url: 'https://www.tradingview.com/support/solutions/43000591664-rectangle/' },
        { icon: 'learn', title: 'Investopedia: How to Read Price Action', desc: 'Foundation guide on reading raw price action without relying on indicators.', url: 'https://www.investopedia.com/articles/active-trading/110714/introduction-price-action-trading-strategies.asp' },
        { icon: 'chart', title: 'CME Group: Identifying Support & Resistance', desc: 'Official course on finding key price levels where institutional orders cluster.', url: 'https://www.cmegroup.com/education/courses/technical-analysis/support-and-resistance.html' },
        { icon: 'learn', title: 'TrendSpider: Fresh vs Tested Supply & Demand Zones', desc: 'Visual guide explaining why untested zones are stronger than revisited ones.', url: 'https://trendspider.com/learning-center/what-are-supply-and-demand-zones/' }
      ]}
    ],
    quiz: [
      { question: 'What are the four steps of the trade execution workflow?', options: ['Buy, Hold, Sell, Repeat', 'Scan, Spot, Anticipate, Execute', 'Research, Analyze, Enter, Exit', 'Indicator, Signal, Trigger, Profit'], correct: 1, explanation: 'The four-step workflow is: Scan for imbalance areas, Spot institutional footprints, Anticipate by planning your S.E.T. before price arrives, Execute when price hits your trigger.' },
      { question: 'What indicates a strong institutional footprint at a zone?', options: ['Slow, grinding price movement away from the zone', 'A zone tested many times', 'Price left the area rapidly and the zone has not been revisited', 'High RSI reading near the zone'], correct: 2, explanation: 'A fast departure from a zone means large unfilled orders remain. A fresh, untested zone is stronger because those orders haven\'t been partially filled yet.' },
      { question: 'Should technical indicators be your primary reason to enter a trade?', options: ['Yes, always use at least 3 indicators', 'No, they should only be a secondary backup', 'Yes, but only moving averages', 'It depends on the timeframe'], correct: 1, explanation: 'Technical indicators should only be a secondary backup. Your primary tools are supply/demand zones, price action at those zones, and the S.E.T. rule.' },
      { question: 'How do you confirm an uptrend using supply and demand?', options: ['RSI above 70', 'Price making higher demand zones and breaking through supply zones', 'Moving average crossover', '3 green candles in a row'], correct: 1, explanation: 'An uptrend is confirmed by higher demand zones forming, supply zones being broken/absorbed, and fresh demand zones remaining untested below current price.' }
    ]
  },
  {
    id: 'm9',
    title: 'Visual Guide: Reading Volume Bars & Spotting Institutional Surges',
    subtitle: 'Learn exactly what volume looks like on your screen and how to identify when institutional money is entering or exiting.',
    sections: [
      { title: 'Why This Module Exists', content: 'Module 3 taught you that tracking volume surges is Pillar 2 of the Master Surge Strategy — but it did not show you what a volume surge actually looks like on your screen. This module fills that gap. You will learn to read volume bars, distinguish normal volume from institutional surges, and use volume as confirmation before entering a trade.\n\nRemember: volume is a secondary confirmation tool, not your primary entry signal. Your primary tools remain supply/demand zones and price action. Volume simply tells you whether the move has institutional conviction behind it.', type: 'text' },
      { title: 'What Volume Bars Are', content: 'Volume bars appear as vertical bars along the bottom of your price chart. Each bar represents the total number of shares (or contracts) traded during that time period — whether it is a 1-minute candle, a daily candle, or a weekly candle.\n\nTall bar = Many shares traded during that period\nShort bar = Few shares traded during that period\n\nMost charting platforms color volume bars green when the price closed higher than it opened, and red when the price closed lower. This color coding helps you quickly see whether the volume was associated with buying pressure or selling pressure.\n\nKey principle: Volume tells you the intensity behind a price move. A big price move on low volume is suspect. A big price move on high volume has institutional weight behind it.', type: 'text' },
      { title: 'Normal Volume vs. Institutional Surges', content: 'On any chart, volume fluctuates naturally throughout the day. To spot an institutional surge, you need to understand what "normal" looks like first.\n\nNormal Volume Characteristics:\n— Bars are relatively similar in height day to day\n— Slight increases at market open (first 30 minutes) and close (last 30 minutes) are normal\n— Mid-day volume tends to be the lowest\n— No single bar dramatically towers over the others\n\nInstitutional Volume Surge Characteristics:\n— A volume bar that is 2x to 5x (or more) the height of the average recent bars\n— Often appears suddenly, breaking the normal rhythm of volume\n— Frequently occurs at or near supply/demand zones (confirming institutional orders are being filled)\n— May cluster over 2–3 consecutive bars as a large order is executed in pieces\n\nThe visual test is simple: if a volume bar looks dramatically taller than the bars around it, something significant happened. That is the footprint you are looking for.', type: 'text' },
      { title: 'Volume Surge Quick Reference', type: 'stats', stats: [
        { num: '2-5x', lbl: 'Above Average = Surge' },
        { num: 'Green', lbl: 'Bullish Volume' },
        { num: 'Red', lbl: 'Bearish Volume' },
        { num: '80-90%', lbl: 'Institutional Share' }
      ]},
      { title: 'How to Read Volume at Supply & Demand Zones', content: 'Volume becomes most meaningful when price is at or near a supply or demand zone you have already identified. Here is what to look for:\n\nAt a Demand Zone (potential long entry):\n— Price drops into your identified demand zone\n— Volume surges as price reaches the zone (institutions are buying)\n— Price begins to reverse upward on continued high volume\n— This confirms the demand zone is active and institutional buyers are present\n— This is your green light to execute your pre-planned long entry\n\nAt a Supply Zone (potential short entry):\n— Price rises into your identified supply zone\n— Volume surges as price reaches the zone (institutions are selling)\n— Price begins to reverse downward on continued high volume\n— This confirms the supply zone is active and institutional sellers are present\n— This is your green light to execute your pre-planned short entry\n\nRed flag — Volume dries up at a zone:\nIf price reaches your zone but volume stays flat or below average, the zone may be exhausted. Institutional orders may have been filled on previous visits. Consider skipping the trade and waiting for a better setup.', type: 'text' },
      { title: 'Volume Divergence Warning Signs', content: 'Volume divergence occurs when price and volume tell different stories. This is one of the most powerful warning signals you can learn to read.\n\nBearish Divergence (Warning: Uptrend May Be Ending):\n— Price is making new highs (moving up)\n— But volume is decreasing with each new high\n— This means fewer institutions are participating in the move\n— The uptrend is losing conviction and may reverse\n\nBullish Divergence (Warning: Downtrend May Be Ending):\n— Price is making new lows (moving down)\n— But volume is decreasing with each new low\n— This means selling pressure is drying up\n— The downtrend is losing momentum and may reverse\n\nWhen you see divergence, it does not mean immediately reverse your position. It means be cautious — the current trend may be running out of institutional fuel. Tighten your stops and be ready for a potential change in direction.', type: 'text' },
      { title: 'Practical Volume Checklist', content: 'Before every trade, ask yourself these volume questions:\n\n1. Is current volume above or below average for this asset?\n2. Was there a volume surge when price entered my zone?\n3. Is volume confirming the direction I want to trade (green bars for longs, red bars for shorts)?\n4. Is there any volume divergence that warns against this trade?\n5. Did volume cluster at the base of the move that created my zone (confirming institutional origin)?\n\nIf volume confirms your zone and direction → proceed with your S.E.T.\nIf volume contradicts your zone or shows divergence → skip the trade and wait.\n\nRemember: No volume confirmation, no trade. Let volume be your institutional lie detector.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'chart', title: 'TradingView: Understanding Volume Bars', desc: 'Interactive guide to reading volume bars on live charts with real-time data.', url: 'https://www.tradingview.com/support/solutions/43000502038-volume/' },
        { icon: 'learn', title: 'Investopedia: Volume Analysis — How to Use Volume in Trading', desc: 'Comprehensive guide to interpreting volume patterns and surges.', url: 'https://www.investopedia.com/articles/technical/02/010702.asp' },
        { icon: 'chart', title: 'CME Group: Volume and Open Interest as Technical Indicators', desc: 'Official CME course on using volume to confirm price moves in futures.', url: 'https://www.cmegroup.com/education/courses/technical-analysis/volume-and-open-interest-as-technical-indicators.html' },
        { icon: 'learn', title: 'StockCharts: Volume Analysis ChartSchool', desc: 'Visual education on volume patterns, surges, and divergence with annotated chart examples.', url: 'https://school.stockcharts.com/doku.php?id=technical_indicators:volume' }
      ]}
    ],
    quiz: [
      { question: 'What does a volume bar that is 3x taller than surrounding bars indicate?', options: ['A glitch in the chart data', 'Normal market activity', 'A likely institutional volume surge', 'The market is about to close'], correct: 2, explanation: 'A volume bar 2x to 5x above average indicates significant institutional activity — the footprint of big money entering or exiting positions.' },
      { question: 'What does it mean when price makes new highs but volume is decreasing?', options: ['Strong bullish confirmation', 'Bearish divergence — uptrend may be weakening', 'Volume does not matter in uptrends', 'You should immediately buy more'], correct: 1, explanation: 'When price rises but volume drops, fewer institutions are participating. This bearish divergence warns the uptrend may be losing conviction.' },
      { question: 'What should you do if price reaches your demand zone but volume stays flat?', options: ['Enter the trade anyway', 'Double your position size', 'Consider skipping — the zone may be exhausted', 'Switch to a supply zone trade'], correct: 2, explanation: 'Flat volume at a zone suggests institutional orders may have been filled on prior visits. Without volume confirmation, skip the trade and wait for a better setup.' },
      { question: 'Green volume bars generally indicate what?', options: ['The stock is owned by eco-friendly companies', 'Price closed higher than it opened during that period', 'Low trading activity', 'The market is closed'], correct: 1, explanation: 'Green volume bars indicate the price closed higher than it opened, suggesting buying pressure dominated that period.' }
    ]
  },
  {
    id: 'm10',
    title: 'Visual Guide: Recognizing Price Cycle Phases on Your Chart',
    subtitle: 'Learn to visually identify Accumulation, Markup, Distribution, and Markdown phases as they happen.',
    sections: [
      { title: 'Why This Module Exists', content: 'Module 3 taught you that markets move through four repeating phases — Accumulation, Markup, Distribution, and Markdown — and that recognizing which phase you are in is Pillar 1 of the Master Surge Strategy. But it did not show you what each phase actually looks like on a price chart.\n\nThis module gives you the visual fingerprint of each phase so you can identify them in real time. Knowing your current phase determines whether you should be buying, selling, waiting, or protecting profits.', type: 'text' },
      { title: 'The 4 Phases at a Glance', type: 'stats', stats: [
        { num: '1', lbl: 'Accumulation' },
        { num: '2', lbl: 'Markup' },
        { num: '3', lbl: 'Distribution' },
        { num: '4', lbl: 'Markdown' }
      ]},
      { title: 'Phase 1: Accumulation — What It Looks Like', content: 'Accumulation is the phase where institutions are quietly buying at low prices after a decline. On your chart, it looks like this:\n\nVisual Characteristics:\n— Price moves sideways in a range after a prior downtrend (Markdown phase)\n— The range is relatively tight — price bounces between a floor (support) and a ceiling (resistance)\n— Candlesticks are mixed: small green and red bars alternating with no clear direction\n— Volume is generally low and flat, with occasional surges as institutions absorb supply\n— The longer the sideways range lasts, the more accumulation is occurring\n— Multiple demand zones form within or just below this range\n\nWhat Is Happening Behind the Scenes:\nInstitutions are buying large quantities of shares, but doing it slowly and quietly so they do not push the price up prematurely. They want to fill their orders at low prices. The sideways action IS the accumulation.\n\nTrading Implication:\nDo not short during accumulation. Be patient. Prepare your long entry for when price breaks above the range ceiling with volume confirmation — that signals the transition to Markup.', type: 'text' },
      { title: 'Phase 2: Markup — What It Looks Like', content: 'Markup is the phase where price breaks out of the accumulation range and trends upward. This is where most trading profits are made on the long side.\n\nVisual Characteristics:\n— Price breaks above the accumulation range ceiling on strong volume\n— Higher highs and higher lows form a clear staircase pattern upward\n— Green candles dominate, and they tend to be larger than the red candles\n— Pullbacks (temporary dips) are shallow and short-lived\n— Each pullback creates a new, higher demand zone\n— Volume tends to be above average, especially on the up moves\n\nWhat Is Happening Behind the Scenes:\nInstitutional buying is now overwhelming the available supply. The unfilled buy orders from the accumulation phase are now driving price higher. Retail traders begin noticing the trend and pile in, adding fuel.\n\nTrading Implication:\nThis is your primary zone for long entries. Buy pullbacks into demand zones within the markup trend. Apply your S.E.T. rule on every entry. Do not fight the trend by shorting.', type: 'text' },
      { title: 'Phase 3: Distribution — What It Looks Like', content: 'Distribution is the phase where institutions are quietly selling their positions at high prices. On your chart, it mirrors accumulation but at the top of a trend.\n\nVisual Characteristics:\n— Price moves sideways in a range after a prior uptrend (Markup phase)\n— The range is choppy — price whipsaws up and down without making new significant highs\n— Upper wicks (shadows) become prominent — price pushes up during the session but gets rejected and closes lower\n— Volume may spike on down moves as institutions distribute shares to eager retail buyers\n— Multiple supply zones form within or just above this range\n— The overall chart gives a "rounding top" or "flat top" appearance\n\nWhat Is Happening Behind the Scenes:\nInstitutions are selling their accumulated positions to retail traders who are still bullish and buying. The sideways chop is institutions slowly exiting without crashing the price.\n\nTrading Implication:\nDo not chase new long entries during distribution. Tighten stops on existing positions. Prepare short entries for when price breaks below the range floor with volume confirmation — that signals the transition to Markdown.', type: 'text' },
      { title: 'Phase 4: Markdown — What It Looks Like', content: 'Markdown is the phase where price breaks down from the distribution range and trends downward. This is where short traders profit and unprepared long traders suffer.\n\nVisual Characteristics:\n— Price breaks below the distribution range floor on strong volume\n— Lower highs and lower lows form a clear descending staircase pattern\n— Red candles dominate, and they tend to be larger than the green candles\n— Rallies (temporary bounces) are shallow and short-lived\n— Each rally creates a new, lower supply zone\n— Volume tends to spike on the down moves, especially early in the markdown\n— Fear and panic selling accelerate the decline\n\nWhat Is Happening Behind the Scenes:\nInstitutional selling is overwhelming demand. The unfilled sell orders from the distribution phase are driving price lower. Retail traders who bought at the top are now panic selling, adding fuel to the decline.\n\nTrading Implication:\nThis is your primary zone for short entries. Sell rallies into supply zones within the markdown trend. Apply your S.E.T. rule on every entry. Do not fight the trend by buying. Wait for a new accumulation phase to form before considering longs again.', type: 'text' },
      { title: 'Phase Transition Signals', content: 'The most profitable trades happen at phase transitions — when one phase ends and the next begins. Here is what to watch for at each transition:\n\nAccumulation → Markup Transition:\n— Price breaks above the accumulation range ceiling\n— Volume surges on the breakout (institutional commitment)\n— The first pullback after breakout holds above the old ceiling (which becomes new support)\n\nMarkup → Distribution Transition:\n— Price stops making new meaningful highs\n— Upward momentum slows — rallies become shorter and weaker\n— Volume divergence appears (price up, volume down)\n— Price enters a sideways range at the highs\n\nDistribution → Markdown Transition:\n— Price breaks below the distribution range floor\n— Volume surges on the breakdown\n— The first rally after breakdown fails at the old floor (which becomes new resistance)\n\nMarkdown → Accumulation Transition:\n— Selling pressure exhausts — volume on down moves dries up\n— Price stops making new meaningful lows\n— A tight sideways range forms at the lows\n— Early volume surges on small up moves signal quiet institutional buying', type: 'text' },
      { title: 'Common Mistakes in Cycle Reading', content: 'Mistake 1: Trying to predict the exact candle where a phase ends.\nPhases transition gradually over days or weeks, not in a single bar. Be patient and wait for confirmation.\n\nMistake 2: Confusing a pullback in Markup with the start of Distribution.\nPullbacks are short-lived and shallow. Distribution is a sustained sideways range at the highs that lasts days or weeks.\n\nMistake 3: Buying during Markdown because the price "looks cheap."\nPrice can always go lower. A falling price does not mean a demand zone is forming. Wait for an actual accumulation range to develop with flat, sideways price action.\n\nMistake 4: Ignoring volume at transitions.\nPhase transitions without volume confirmation are unreliable. Always require a volume surge to confirm a breakout or breakdown is real.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'chart', title: 'Schwab: Four Stages of the Stock Market Cycle', desc: 'Visual breakdown of all four phases with annotated charts showing each transition.', url: 'https://www.schwab.com/learn/story/four-stages-stock-market-cycles' },
        { icon: 'learn', title: 'Investopedia: Market Cycles — How to Identify and Profit', desc: 'Detailed guide to recognizing each phase with real-world chart examples.', url: 'https://www.investopedia.com/trading/market-cycles-key-maximum-returns/' },
        { icon: 'chart', title: 'Visual Capitalist: Market Cycle Diagram', desc: 'Clean infographic showing phase sequence with investor psychology at each stage.', url: 'https://www.visualcapitalist.com/this-market-cycle-diagram-explains-the-best-time-to-buy-stocks/' },
        { icon: 'learn', title: 'CME Group: Technical Analysis — Trend Identification', desc: 'Official CME course on identifying trends and their phases on futures charts.', url: 'https://www.cmegroup.com/education/courses/technical-analysis/trend-identification.html' }
      ]}
    ],
    quiz: [
      { question: 'What does the Accumulation phase look like on a chart?', options: ['A sharp upward breakout', 'A sideways range after a decline with mixed small candles and low volume', 'Large red candles falling rapidly', 'A single green candle on huge volume'], correct: 1, explanation: 'Accumulation appears as a sideways range after a prior downtrend, with mixed small candles and generally low volume as institutions quietly buy.' },
      { question: 'During Markup, what pattern do highs and lows form?', options: ['Lower highs and lower lows', 'Random scattered pattern', 'Higher highs and higher lows in a staircase', 'All candles are the same size'], correct: 2, explanation: 'Markup is characterized by higher highs and higher lows forming a clear upward staircase pattern, with green candles dominating.' },
      { question: 'What is the key visual sign that Distribution is occurring (not just a pullback)?', options: ['One red candle appears', 'Volume drops to zero', 'A sustained sideways range at the highs lasting days or weeks', 'Price drops 50% immediately'], correct: 2, explanation: 'Distribution is a sustained sideways range at the highs that lasts days or weeks, not just a brief pullback. Upper wicks become prominent as price gets rejected at highs.' },
      { question: 'What confirms an Accumulation → Markup transition?', options: ['A news article says the stock is good', 'Price breaks above the accumulation range on a volume surge', 'RSI crosses above 50', 'The price is below the 200-day moving average'], correct: 1, explanation: 'The transition is confirmed when price breaks above the accumulation range ceiling with a volume surge showing institutional commitment, and the first pullback holds above the old ceiling.' }
    ]
  },
  {
    id: 'm11',
    title: 'Visual Guide: Chart Patterns at Supply & Demand Zones',
    subtitle: 'Learn the specific candlestick and price patterns that reveal institutional activity at your zones.',
    sections: [
      { title: 'Why This Module Exists', content: 'Throughout Modules 2, 3, and 8, you learned to identify supply and demand zones and scan for institutional footprints. But the training noted that specific chart patterns were not described or shown visually. This module fills that critical gap.\n\nYou will learn six key price patterns that appear at supply and demand zones when institutional orders are being filled. These are not traditional "textbook" chart patterns — they are raw price action signatures that reveal the presence of big money at your zones.\n\nRemember the academy philosophy: these patterns are read from the OHLC price bars themselves, not from lagging indicators. You are reading what the market is doing, not what an indicator says it might be doing.', type: 'text' },
      { title: 'Pattern 1: The Explosive Departure', content: 'What It Is:\nThe single most important pattern for identifying institutional zones. An explosive departure is when price leaves an area with extreme speed and force — multiple large-bodied candles in the same direction with little to no overlap between them.\n\nWhat It Looks Like on Your Chart:\n— A series of 2–5 large candles moving rapidly in one direction\n— Very small or no wicks (shadows) in the direction of movement\n— Little or no overlap between consecutive candle bodies\n— Volume surges during the departure\n— The move covers a large price distance in a short time\n\nWhat It Means:\nA massive institutional order was executed so aggressively that it overwhelmed all opposing orders. The speed of departure indicates a large portion of the order was likely NOT filled — creating a strong zone of unfilled orders at the origin point.\n\nHow to Use It:\nMark the base of the explosive departure (the last candle before the rapid move began) as your demand zone (if the move was upward) or supply zone (if the move was downward). This is one of the highest-probability zones you can trade.', type: 'text' },
      { title: 'Pattern 2: The Basing Candle', content: 'What It Is:\nA small-bodied candle (or series of small candles) that appears at the origin point just before an explosive move. The basing candle represents the moment when institutional orders are being quietly loaded before the big move.\n\nWhat It Looks Like on Your Chart:\n— One or more candles with very small bodies (open and close are close together)\n— Can be green or red — the color matters less than the small size\n— Often has small wicks on both sides (showing indecision)\n— Appears directly before a large, aggressive move in one direction\n— Volume on the basing candle may be average or slightly above average\n\nWhat It Means:\nThe small body shows equilibrium — supply and demand are briefly balanced as the institution loads its order. Then the balance breaks explosively as the order overwhelms one side.\n\nHow to Use It:\nThe basing candle IS your zone. Draw your demand or supply zone from the high to the low of the basing candle (or the cluster of basing candles). This narrow zone gives you a precise entry area and a tight stop, improving your reward-to-risk ratio.', type: 'text' },
      { title: 'Pattern 3: The Engulfing Candle at a Zone', content: 'What It Is:\nA large candle that completely "engulfs" (covers the entire range of) the previous candle. When this appears at a supply or demand zone, it signals a decisive shift in control from buyers to sellers (or vice versa).\n\nWhat It Looks Like on Your Chart:\n\nBullish Engulfing at a Demand Zone:\n— Price drops into your demand zone\n— A red (down) candle forms at the zone\n— The next candle is a large green (up) candle whose body completely covers the previous red candle\'s body\n— Volume is higher on the green engulfing candle\n— Signal: Institutional buyers have taken control at this zone\n\nBearish Engulfing at a Supply Zone:\n— Price rises into your supply zone\n— A green (up) candle forms at the zone\n— The next candle is a large red (down) candle whose body completely covers the previous green candle\'s body\n— Volume is higher on the red engulfing candle\n— Signal: Institutional sellers have taken control at this zone\n\nHow to Use It:\nAn engulfing candle at your pre-identified zone is strong confirmation to execute your planned S.E.T. entry. The engulfing candle tells you the zone is active and institutions are present.', type: 'text' },
      { title: 'Key Patterns at a Glance', type: 'stats', stats: [
        { num: '1', lbl: 'Explosive Departure' },
        { num: '2', lbl: 'Basing Candle' },
        { num: '3', lbl: 'Engulfing at Zone' },
        { num: '4', lbl: 'Rejection Wicks' }
      ]},
      { title: 'Pattern 4: Rejection Wicks (Pin Bars) at Zones', content: 'What It Is:\nA candle with a very long wick (shadow) that extends into your zone, but a small body that closes back outside the zone. The long wick shows that price entered the zone, triggered institutional orders, and was immediately "rejected" back out.\n\nWhat It Looks Like at a Demand Zone:\n— A candle with a long lower wick extending down into the demand zone\n— The body is small and closes near the high of the candle\n— The lower wick is at least 2–3 times longer than the body\n— This is sometimes called a "hammer" or "pin bar"\n— Signal: Institutional buyers aggressively defended this demand zone\n\nWhat It Looks Like at a Supply Zone:\n— A candle with a long upper wick extending up into the supply zone\n— The body is small and closes near the low of the candle\n— The upper wick is at least 2–3 times longer than the body\n— This is sometimes called a "shooting star" or inverted pin bar\n— Signal: Institutional sellers aggressively defended this supply zone\n\nHow to Use It:\nA rejection wick at your zone is a high-confidence signal. The long wick IS the institutional order being filled. Set your entry near the close of the rejection candle, your stop beyond the wick tip, and your target at 3:1.', type: 'text' },
      { title: 'Pattern 5: The Gap at a Zone (Imbalance Windows)', content: 'What It Is:\nA price gap occurs when the next candle\'s open is significantly higher or lower than the previous candle\'s close, leaving an empty space on the chart. Gaps at or near zones are powerful evidence of institutional urgency.\n\nWhat It Looks Like on Your Chart:\n— A visible empty space between two consecutive candles\n— The close of one candle and the open of the next do not overlap\n— The gap often forms on high volume\n— In futures (23-hour access), gaps are rarer — making them even more significant when they do appear\n\nWhat It Means:\nA gap shows that institutional buying or selling was so aggressive that it skipped over an entire price range. The empty space represents prices where no one was willing to trade — a pure imbalance.\n\nHow to Use It:\nGaps often act as supply or demand zones themselves. An unfilled gap (price has not returned to close it) represents an area of extreme institutional conviction. When price eventually returns to test the gap, treat it like a fresh supply or demand zone and apply your S.E.T. rule.', type: 'text' },
      { title: 'Pattern 6: The Squeeze Before the Move', content: 'What It Is:\nA series of candles that progressively get smaller in range (body and wicks both shrink), creating a visual "squeeze" or compression. This happens when supply and demand are tightly balanced just before a major move.\n\nWhat It Looks Like on Your Chart:\n— Each consecutive candle has a smaller range than the one before it\n— The overall pattern looks like a triangle or wedge compressing into a point\n— Volume typically decreases during the squeeze (low participation while waiting)\n— The squeeze often occurs just before price reaches a major supply or demand zone\n— The resolution is usually an explosive move in one direction with a volume surge\n\nWhat It Means:\nBoth institutional buyers and sellers are waiting. The decreasing range shows neither side is willing to commit. When one side finally overpowers the other, the resulting move is often violent and fast because of the built-up pressure.\n\nHow to Use It:\nWhen you see a squeeze forming near your supply or demand zone, it confirms that a major move is coming. Do not try to predict the direction during the squeeze. Wait for the breakout or breakdown with volume confirmation, then apply your S.E.T. to trade in the direction of the resolution.', type: 'text' },
      { title: 'Putting It All Together: The Confirmation Stack', content: 'No single pattern should be traded in isolation. The strongest trades occur when multiple patterns confirm the same zone. Here is how to stack confirmations:\n\nLevel 1 (Minimum Required):\n— You have a pre-identified supply or demand zone from Module 8\'s Scan-Spot workflow\n— Price arrives at your zone\n\nLevel 2 (Good Confirmation):\n— One of the six patterns above appears at the zone (engulfing, rejection wick, basing candle, etc.)\n— Volume is above average at the zone\n\nLevel 3 (Strong Confirmation):\n— Two or more patterns appear at the zone\n— Volume surges confirm institutional presence\n— Multiple timeframes show the same zone (daily + 4-hour alignment from Module 8)\n— The trade direction aligns with the current price cycle phase (from Module 10)\n\nThe more confirmations you stack, the higher the probability of your trade. But remember — even with maximum confirmation, always apply your S.E.T. rule and never risk more than 1%. No setup is 100% guaranteed.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'chart', title: 'Investopedia: Candlestick Patterns Every Trader Should Know', desc: 'Visual guide to key candlestick patterns with annotated chart examples.', url: 'https://www.investopedia.com/articles/active-trading/062315/which-candlestick-patterns-work.asp' },
        { icon: 'learn', title: 'TrendSpider: Pin Bar Trading Strategy', desc: 'Detailed guide to rejection wicks (pin bars) with real chart examples at zones.', url: 'https://trendspider.com/learning-center/pin-bar-trading-strategy/' },
        { icon: 'chart', title: 'CME Group: Price Gaps and Their Analysis', desc: 'Official CME education on gap types and how to trade them in futures markets.', url: 'https://www.cmegroup.com/education/courses/technical-analysis/understanding-price-gaps.html' },
        { icon: 'learn', title: 'StockCharts: Introduction to Candlestick Charting', desc: 'Foundation guide to reading individual and combination candlestick patterns.', url: 'https://school.stockcharts.com/doku.php?id=chart_analysis:introduction_to_candlesticks' }
      ]}
    ],
    quiz: [
      { question: 'What is the most important pattern for identifying a strong institutional zone?', options: ['A moving average crossover', 'The Explosive Departure — fast, aggressive move away from an area', 'Three identical candles in a row', 'A candle that closes exactly at its open'], correct: 1, explanation: 'An Explosive Departure — multiple large candles leaving an area with extreme speed — indicates a massive institutional order that likely left unfilled orders behind, creating a high-probability zone.' },
      { question: 'What does a long lower wick (rejection wick) at a demand zone signal?', options: ['Sellers are in complete control', 'Price will continue falling', 'Institutional buyers aggressively defended the zone', 'The zone has been permanently broken'], correct: 2, explanation: 'A long lower wick at a demand zone shows that price entered the zone, triggered institutional buy orders, and was rejected back up — confirming active institutional buying at that level.' },
      { question: 'What is a Basing Candle and how do you use it?', options: ['A large candle that shows strong trend continuation', 'A small-bodied candle at the origin of an explosive move that defines your exact zone', 'Any candle that appears on Monday morning', 'A candle with no wicks at all'], correct: 1, explanation: 'A basing candle is a small-bodied candle appearing just before an explosive move. It represents institutions loading orders. Draw your zone from its high to low for a precise entry area.' },
      { question: 'What does the "Confirmation Stack" recommend for the strongest trades?', options: ['Use only one indicator signal', 'Stack multiple confirmations: zone + pattern + volume + timeframe alignment + cycle phase', 'Trade every zone regardless of confirmation', 'Wait for a news announcement'], correct: 1, explanation: 'The strongest trades stack multiple confirmations: a pre-identified zone, a price pattern at the zone, volume surge, multi-timeframe alignment, and cycle phase alignment. More confirmations = higher probability.' }
    ]
  }
]
