  // ── PASTE BELOW after the closing } of m11 (add a comma after m11's closing brace first) ──
  {
    id: 'm12',
    title: 'Market Performance, Trading Psychology & Valuation',
    subtitle: 'Learn how diversified portfolios survive downturns, how psychology traps traders, and how to measure true market value.',
    sections: [
      { title: '2022 Market Performance: Stock Decline vs. Recovery', content: 'In 2022, the stock market dropped approximately 20%. But a diversified portfolio with an options strategy could soften the decline and accelerate recovery. Here is a real-world example:\n\nStarting position: $20,000 invested in S&P 500\nS&P 500 prices during 2022:\n\u2022 February 19: $338\n\u2022 March 23: $218 (the bottom)\n\u2022 August 12: $338 (recovery)\n\nShares purchased: $20,000 \u00f7 $338 \u2248 59 shares\nGain from recovery: 59 shares \u00d7 $120 per share = $7,080\nNet after losses: $7,080 \u2212 $2,080 = $5,000 total profit\nEnd value: $25,000 (original principal + profit)\n\nThe key takeaway: market drops do not always equal portfolio destruction when you are diversified and use strategic options positioning to manage risk during volatility.', type: 'text' },
      { title: '2022 Recovery Breakdown', type: 'stats', stats: [
        { num: '\u201320%', lbl: 'S&P 500 Drop in 2022' },
        { num: '59', lbl: 'Shares at $338' },
        { num: '$7,080', lbl: 'Gain from Recovery' },
        { num: '$25,000', lbl: 'End Portfolio Value' }
      ]},
      { title: 'Core Trading Principles', content: '"Your trend is your friend until the bend at the end." This classic trading maxim captures a fundamental truth: follow strong market direction, but always watch for reversals. Trends can persist far longer than most traders expect, but when they end, they can reverse violently.\n\nAnother critical principle: never specialize in a single asset. Diversification across asset classes \u2014 stocks, options, futures, bonds \u2014 reduces overall portfolio risk and smooths returns over time. The traders who survive long-term are the ones who spread risk intelligently.\n\nThese two principles \u2014 trend following and diversification \u2014 form the foundation of sustainable trading.', type: 'text' },
      { title: 'Three Pillars of Trading Mastery', content: 'Mastery in trading requires three interconnected pillars working together:\n\n1. Knowledge \u2014 Understand market structure, tools, instruments, and how trends develop. Without knowledge, every trade is a gamble. Study supply and demand, chart patterns, risk management, and the mechanics of your chosen vehicles (stocks, options, futures).\n\n2. Skill \u2014 Execute consistently and without emotional bias. Skill is the bridge between knowing what to do and actually doing it under pressure. It comes from practice, repetition, and disciplined execution of your trading plan.\n\n3. Tools \u2014 Use professional-grade charts, risk calculators, analytics platforms, and position sizing formulas. The right tools give you an edge in speed, accuracy, and confidence. Without proper tools, even skilled traders make avoidable mistakes.\n\nNo single pillar is sufficient on its own. Knowledge without skill is theory. Skill without tools is handicapped. Tools without knowledge is dangerous.', type: 'text' },
      { title: 'The Dunning\u2013Kruger Effect in Trading', content: 'The Dunning\u2013Kruger Effect is a cognitive bias where people with low skill overestimate their ability because they lack the knowledge to recognize their own mistakes. In trading, this is one of the most dangerous psychological traps.\n\nThe four phases every trader passes through:\n\nPeak of Mt. Stupid \u2014 High confidence, low competence. You\'ve had a few winning trades and think you\'ve "figured it out." This is where most account blow-ups happen. You take oversized positions, ignore risk management, and believe you\'re special.\n\nValley of Despair \u2014 Reality hits. Losses pile up. You realize how much you don\'t know. Confidence crashes. Many traders quit here. But this is actually where real growth begins \u2014 because awareness of your limitations is the first step to improvement.\n\nSlope of Enlightenment \u2014 Gradual improvement through structured skill-building. You start following rules, studying consistently, and managing risk properly. Wins become more consistent. You develop humility and respect for the market.\n\nPlateau of Sustainability \u2014 True expertise. Confidence stabilizes because it\'s based on real skill, not luck. You trade your plan, manage risk, and let the system work. This is where the top 5% operate.', type: 'text' },
      { title: 'Dunning\u2013Kruger Phases', type: 'stats', stats: [
        { num: 'Phase 1', lbl: 'Peak of Mt. Stupid' },
        { num: 'Phase 2', lbl: 'Valley of Despair' },
        { num: 'Phase 3', lbl: 'Slope of Enlightenment' },
        { num: 'Phase 4', lbl: 'Plateau of Sustainability' }
      ]},
      { title: 'The Shiller P/E Ratio (CAPE)', content: 'The Shiller P/E Ratio \u2014 also called the P/E 10 or CAPE (Cyclically Adjusted Price-to-Earnings) ratio \u2014 is one of the most important valuation tools for understanding whether the stock market is overvalued or undervalued.\n\nHow it works: The Shiller P/E adjusts earnings for inflation over a 10-year period, giving a more accurate long-term valuation of the stock market by removing short-term earnings noise.\n\nWhy it matters: A regular P/E ratio uses only last year\'s earnings, which can be distorted by temporary spikes or dips. The Shiller P/E smooths out this volatility and accounts for inflation, providing a much better reflection of true market value.\n\nWhen the Shiller P/E is historically high (above 25\u201330), markets have tended to deliver lower future returns. When it\'s historically low (below 15), markets have tended to deliver higher future returns. This doesn\'t predict short-term moves, but it provides crucial context for long-term positioning and risk assessment.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'chart', title: 'Multpl: Current Shiller P/E Ratio', desc: 'Live chart showing the historical Shiller P/E ratio for the S&P 500 dating back to 1870.', url: 'https://www.multpl.com/shiller-pe' },
        { icon: 'learn', title: 'Schwab: Four Stages of the Stock Market Cycle', desc: 'Understanding accumulation, markup, distribution, and markdown phases.', url: 'https://www.schwab.com/learn/story/four-stages-stock-market-cycles' },
        { icon: 'learn', title: 'Verywell Mind: Dunning\u2013Kruger Effect Explained', desc: 'Deep dive into the cognitive bias that affects traders at every experience level.', url: 'https://www.verywellmind.com/an-overview-of-the-dunning-kruger-effect-4160740' }
      ]}
    ],
    quiz: [
      { question: 'In the 2022 example, what was the approximate total end value of a $20,000 diversified portfolio after recovery?', options: ['$20,000', '$22,500', '$25,000', '$30,000'], correct: 2, explanation: 'The portfolio recovered to approximately $25,000 total \u2014 the original $20,000 principal plus $5,000 in net profit from the recovery.' },
      { question: 'What does the phrase "Your trend is your friend until the bend at the end" mean?', options: ['Always trade against the trend for maximum profit', 'Follow strong market direction but watch for reversals', 'Trends never end so always hold your position', 'Only trade during the first hour of market open'], correct: 1, explanation: 'The phrase means you should follow the prevailing trend direction, but stay alert for signs of reversal \u2014 trends eventually end and can reverse sharply.' },
      { question: 'During which Dunning\u2013Kruger phase do most trading account blow-ups occur?', options: ['Valley of Despair', 'Slope of Enlightenment', 'Peak of Mt. Stupid', 'Plateau of Sustainability'], correct: 2, explanation: 'The Peak of Mt. Stupid is where traders have high confidence but low competence \u2014 they take oversized positions and ignore risk management, leading to major losses.' },
      { question: 'What advantage does the Shiller P/E have over a standard P/E ratio?', options: ['It only uses last quarter\'s earnings', 'It adjusts earnings for inflation over a 10-year period', 'It measures daily trading volume', 'It predicts exact market tops and bottoms'], correct: 1, explanation: 'The Shiller P/E smooths earnings over 10 years and adjusts for inflation, removing short-term noise and giving a more accurate picture of true market valuation.' },
      { question: 'Which is NOT one of the Three Pillars of Trading Mastery?', options: ['Knowledge', 'Skill', 'Luck', 'Tools'], correct: 2, explanation: 'The three pillars are Knowledge, Skill, and Tools. Luck is not a pillar \u2014 successful trading is built on systematic preparation, not chance.' }
    ]
  },
  {
    id: 'm13',
    title: 'Options Fundamentals: Calls, Puts & Basic Mechanics',
    subtitle: 'Understand what options are, how calls and puts work, and why options give you flexibility and control with defined risk.',
    sections: [
      { title: 'What Is an Option?', content: 'An option is a contract that gives you the right, but not the obligation, to buy or sell a stock at a specific price in the future.\n\nThink of it like putting a reservation on a stock. You pay a small amount of money called a premium, and in exchange, you lock in a price today \u2014 even if the real price changes later.\n\nTwo defining characteristics of every option:\n\u2022 Strike Price \u2014 the locked-in price you can buy or sell at\n\u2022 Expiration Date \u2014 when the contract expires (can range from 1 day to 3 years)\n\nOne contract controls 100 shares of stock. Options are quoted per share, so multiply by 100 for the total cost. For example, an option quoted at $3.00 actually costs $300 total.', type: 'text' },
      { title: 'Option Contract Basics', type: 'stats', stats: [
        { num: '100', lbl: 'Shares Per Contract' },
        { num: '\u00d7100', lbl: 'Quote \u00d7 100 = Total Cost' },
        { num: '1 Day\u20133 Yrs', lbl: 'Expiration Range' },
        { num: 'Premium', lbl: 'Maximum Loss for Buyers' }
      ]},
      { title: 'Call Options \u2014 The Right to Buy', content: 'A call option gives you the right to buy a stock at the strike price. You buy calls when you think the stock will go up.\n\nExample: You buy a call option to buy Apple at $100 (the strike price). Apple rises to $130. You can still buy at $100 \u2014 locking in a $30 per share advantage.\n\nCall option characteristics:\n\u2022 You want the stock price to go UP\n\u2022 Profit potential is unlimited (stock can keep rising)\n\u2022 Your maximum risk is limited to the premium you paid\n\u2022 The call becomes more valuable as the stock rises above the strike price\n\nWhen you buy a stock, you need the full share price. When you buy a call option, you only pay the premium \u2014 a fraction of the cost \u2014 while controlling the same 100 shares.', type: 'text' },
      { title: 'Put Options \u2014 The Right to Sell', content: 'A put option gives you the right to sell a stock at the strike price. You buy puts when you think the stock will go down.\n\nExample: You buy a put option to sell Tesla at $200 (the strike price). Tesla falls to $150. You can still sell at $200 \u2014 protecting yourself from the $50 per share drop.\n\nPut option characteristics:\n\u2022 You want the stock price to go DOWN\n\u2022 Profit potential grows as the stock falls further below the strike\n\u2022 Your maximum risk is limited to the premium you paid\n\u2022 The put becomes more valuable as the stock drops below the strike price\n\nPuts act like insurance for your portfolio. If you own stocks and buy protective puts, you cap your downside while keeping your upside potential.', type: 'text' },
      { title: 'Why People Use Options', content: 'Options serve three primary purposes:\n\n1. To Make Money With Less Money \u2014 Options allow you to control a stock without buying the whole thing. One contract gives you exposure to 100 shares at a fraction of the share price. This is the core leverage advantage.\n\n2. To Protect Investments \u2014 Options work like insurance for your portfolio. If you own stocks and are worried about a decline, buying put options caps your potential loss at a known amount.\n\n3. To Reduce and Define Risk \u2014 When you buy an option, the absolute maximum you can lose is the premium you paid. Nothing more. This makes options ideal for the 1% risk rule \u2014 you always know your worst-case scenario before entering the trade.\n\nThe key idea: Options = flexibility and control. You lock in a price today, decide later whether to use it, and can profit whether the market goes up or down depending on the option you choose.', type: 'text' },
      { title: 'Simple Call Option Example', content: 'Let\'s walk through a complete trade to see how options work in practice:\n\nYou buy a Call Option:\n\u2022 Strike price: $50\n\u2022 Current stock price: $50\n\u2022 Premium (your cost): $5\n\u2022 Stock later rises to: $70\n\nCalculation:\n\u2022 You buy at $50 (your strike), sell at $70 (market price)\n\u2022 Gross profit: $20 per share\n\u2022 Minus the $5 premium = $15 actual profit per share\n\u2022 Since 1 contract = 100 shares: $15 \u00d7 100 = $1,500 total profit\n\u2022 Your total investment was only $500 (the premium)\n\nIf the stock stayed below $50 instead, the most you lose is the $5 per share premium ($500 total). That\'s it. Your risk was defined from the start.\n\nThis is why options are powerful: small investment, large potential return, and your maximum loss is always known in advance.', type: 'text' },
      { title: '100 Shares vs. 1 Call Option', type: 'table', headers: ['Method', 'Controls', 'Cost', 'Max Loss'], rows: [
        ['Buy 100 shares at $50', '100 shares', '$5,000', '$5,000'],
        ['Buy 1 call option', 'Right to 100 shares', '~$500', '$500']
      ]},
      { title: 'Important: Sideways Movement', content: 'There is one critical risk to understand: call and put options lose value when the stock goes sideways \u2014 meaning it stays at or near the same price.\n\nThis happens because of time decay (Theta). Every day that passes, the option loses a small amount of value, even if the stock doesn\'t move. The closer you get to expiration, the faster this decay accelerates.\n\nThis is why direction and timing both matter in options trading. You need the stock to move in your expected direction before expiration, or the option will lose value regardless of whether you picked the right direction.\n\nThe next modules cover the Greeks (Delta, Vega, Theta) that measure exactly how these forces affect your option\'s price.', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'learn', title: 'Options Industry Council: How Options Work', desc: 'Beginner-friendly explanation of calls, puts, and basic options mechanics.', url: 'https://www.optionseducation.org/optionsoverview/options-basics' },
        { icon: 'chart', title: 'CME Group: Understanding Options Expiration & P/L', desc: 'Visual guides showing how options profit and loss works at expiration.', url: 'https://www.cmegroup.com/education/courses/introduction-to-options' },
        { icon: 'learn', title: 'SoFi: Strike Price Explained', desc: 'Clear breakdown of how strike prices work and how to choose them.', url: 'https://www.sofi.com/learn/content/strike-price/' }
      ]}
    ],
    quiz: [
      { question: 'What does an option contract give you?', options: ['The obligation to buy or sell a stock', 'The right, but not the obligation, to buy or sell a stock at a specific price', 'Guaranteed profit if the stock moves in any direction', 'Ownership of 100 shares immediately'], correct: 1, explanation: 'An option gives you the RIGHT, but not the obligation, to buy or sell at a specific price (the strike price) before expiration.' },
      { question: 'When do you buy a call option?', options: ['When you think the stock will go down', 'When you think the stock will stay the same', 'When you think the stock will go up', 'When you want to sell shares you already own'], correct: 2, explanation: 'A call option gives you the right to BUY at the strike price \u2014 you profit when the stock rises above that price.' },
      { question: 'In the call option example (strike $50, premium $5, stock rises to $70), what is the actual profit per share?', options: ['$20', '$15', '$5', '$70'], correct: 1, explanation: '$70 market price \u2212 $50 strike = $20 gross profit. Minus the $5 premium = $15 actual profit per share.' },
      { question: 'What is the maximum loss when you BUY an option?', options: ['Unlimited \u2014 you could lose everything', '50% of the stock price', 'The premium you paid', 'The strike price minus the stock price'], correct: 2, explanation: 'When you buy an option, the maximum you can lose is the premium (the price you paid for the contract). Nothing more.' },
      { question: 'Why do options lose value when a stock moves sideways?', options: ['Because the broker charges extra fees', 'Because of time decay (Theta) \u2014 options lose value daily as expiration approaches', 'Because sideways movement triggers automatic sell orders', 'Because the strike price automatically adjusts downward'], correct: 1, explanation: 'Time decay (Theta) causes options to lose value every day, even if the stock doesn\'t move. You need directional movement before expiration to profit.' }
    ]
  },
  {
    id: 'm14',
    title: 'Options Greeks: Delta, Vega & Theta',
    subtitle: 'Master the three forces that control option pricing \u2014 direction, volatility, and time decay.',
    sections: [
      { title: 'What Are the Options Greeks?', content: 'The Options Greeks are measurements that tell you exactly how and why an option\'s price is changing. They remove the guesswork and give you precise insight into the forces acting on your position.\n\nThere are three primary Greeks every trader must understand:\n\nDelta (\u0394) \u2014 Measures direction and speed. How fast does the option price move when the stock moves?\n\nVega \u2014 Measures volatility sensitivity. How much does the option price change when market volatility changes?\n\nTheta (\u0398) \u2014 Measures time decay. How much value does the option lose each day just from time passing?\n\nThink of it this way: Delta tells you about direction, Vega tells you about environment, and Theta tells you about the clock. Together they explain virtually every price movement you see in an option.', type: 'text' },
      { title: 'Greeks Quick Reference', type: 'stats', stats: [
        { num: '\u0394 Delta', lbl: 'Direction + Speed' },
        { num: 'Vega', lbl: 'Volatility + Cost' },
        { num: '\u0398 Theta', lbl: 'Time Decay (Daily)' }
      ]},
      { title: 'Delta (\u0394) \u2014 Direction and Speed', content: 'Delta measures how much an option\'s price changes when the stock price changes by $1. It is expressed as a decimal between 0 and 1.00 for calls (or 0 and \u22121.00 for puts).\n\nIf Delta = 0.70, the option moves 70 cents for every $1 the stock moves. Higher Delta means the option price moves more dramatically. Lower Delta means the option responds more slowly.\n\nReal Example:\n\u2022 Stock price: $100\n\u2022 Option price: $5\n\u2022 Stock rises to $120 (a $20 increase)\n\u2022 Option rises by $15\n\nTo calculate Delta: Option move \u00f7 Stock move = $15 \u00f7 $20 = 0.75\nThis means the option moved at 75% of the stock\'s speed.\n\nKey Delta ranges:\n\u2022 Deep in-the-money options: Delta 0.70\u20131.00 (expensive, moves almost like the stock)\n\u2022 At-the-money options: Delta ~0.50 (moderate cost, moderate movement)\n\u2022 Far out-of-the-money options: Delta 0.10\u20130.30 (cheap, slow movement)\n\nHigher Delta = higher cost + higher sensitivity to price changes. It\'s a trade-off between responsiveness and the premium you pay.', type: 'text' },
      { title: 'Vega \u2014 Volatility Sensitivity', content: 'Vega measures how much the option price changes when the stock\'s implied volatility changes. You always pay more for an option on a high-volatility stock.\n\nLow Vega Environment:\n\u2022 Low volatility \u2014 the stock moves slowly and predictably\n\u2022 Lower option prices (premiums are cheaper)\n\u2022 Less movement, fewer big swings\n\u2022 Lower risk, but also lower opportunity\n\nHigh Vega Environment:\n\u2022 High volatility \u2014 the stock makes large, unpredictable swings\n\u2022 Options cost more (premiums expand)\n\u2022 More opportunity for large profits\n\u2022 But also more opportunity for large losses\n\nWhy this matters: When you buy options during low volatility and volatility then increases, your option gains value from Vega alone \u2014 even if the stock hasn\'t moved much. Conversely, if you buy during high volatility and it drops, your option loses value even if the stock moves in your favor.\n\nHigh Vega = bigger opportunities AND bigger risks. Understanding Vega helps you time your entries and avoid overpaying for options.', type: 'text' },
      { title: 'Volatility Comparison', type: 'table', headers: ['Factor', 'Low Vega', 'High Vega'], rows: [
        ['Option Cost', 'Cheaper premiums', 'Expensive premiums'],
        ['Price Movement', 'Slow, steady moves', 'Large, fast swings'],
        ['Risk Level', 'Lower risk', 'Higher risk'],
        ['Opportunity', 'Limited upside', 'Large profit potential'],
        ['Stock Behavior', 'Stable, predictable', 'Wild, volatile']
      ]},
      { title: 'Theta (\u0398) \u2014 Time Decay', content: 'Theta measures how much value an option loses each day as time passes. This is the "silent killer" of options positions.\n\nCritical facts about Theta:\n\u2022 Options lose value every single day, even if the stock doesn\'t move\n\u2022 Longer-dated options lose time value more slowly\n\u2022 Shorter-dated options lose time value faster\n\u2022 Time decay accelerates as expiration approaches \u2014 the last 30 days are the most destructive\n\nRule of thumb: A 4-month option typically loses around 15% of its value to time decay as the months pass.\n\nTheta always works against you when you are a buyer of options. Every day you hold, the clock is ticking against your position. This is why timing matters \u2014 you need the stock to move in your direction before time decay erodes your premium.\n\nConversely, Theta works in your favor when you are a seller of options. Option sellers collect premium and profit from the passage of time. This is an advanced concept covered in later modules.', type: 'text' },
      { title: 'At the Money (ATM) vs. In the Money (ITM)', content: 'Understanding where your strike price sits relative to the stock price is essential for choosing the right option.\n\nAt the Money (ATM):\n\u2022 The strike price equals (or is very close to) the current stock price\n\u2022 Example: Stock = $100, Strike = $100\n\u2022 ATM options have: highest time decay (Theta), medium Delta (~0.50), and are the most sensitive to price movement\n\u2022 They cost less than ITM options but more than OTM options\n\nIn the Money (ITM):\n\u2022 The option already has built-in (intrinsic) value based on the current stock price\n\u2022 Call option ITM: Stock is ABOVE the strike \u2014 Example: Stock = $120, Strike = $100\n\u2022 Put option ITM: Stock is BELOW the strike \u2014 Example: Stock = $80, Strike = $100\n\u2022 ITM options have: higher Delta (0.70\u20131.00), more stable movement, less time decay impact, but cost significantly more\n\nOut of the Money (OTM):\n\u2022 The option has no intrinsic value yet \u2014 only time value\n\u2022 Call OTM: Stock is BELOW the strike \u2014 Example: Stock = $90, Strike = $100\n\u2022 Put OTM: Stock is ABOVE the strike \u2014 Example: Stock = $110, Strike = $100\n\u2022 OTM options are cheapest but have the lowest probability of profit\n\nChoosing between ATM, ITM, and OTM is a core skill in options trading. It determines your cost, risk, and probability of success.', type: 'text' },
      { title: 'Strike Price Positioning', type: 'table', headers: ['Position', 'Call Example', 'Put Example', 'Delta Range', 'Cost'], rows: [
        ['Deep ITM', 'Stock $120, Strike $80', 'Stock $80, Strike $120', '0.80\u20131.00', 'Highest'],
        ['ITM', 'Stock $120, Strike $100', 'Stock $80, Strike $100', '0.60\u20130.80', 'High'],
        ['ATM', 'Stock $100, Strike $100', 'Stock $100, Strike $100', '~0.50', 'Moderate'],
        ['OTM', 'Stock $90, Strike $100', 'Stock $110, Strike $100', '0.20\u20130.40', 'Low'],
        ['Deep OTM', 'Stock $80, Strike $120', 'Stock $120, Strike $80', '0.05\u20130.20', 'Cheapest']
      ]},
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'learn', title: 'Options Industry Council: The Greeks', desc: 'Complete guide to Delta, Gamma, Theta, Vega, and Rho with interactive examples.', url: 'https://www.optionseducation.org/advancedconcepts/the-greeks' },
        { icon: 'chart', title: 'Fidelity: Options Greeks Overview', desc: 'Visual charts showing how Delta, Theta, and Vega change across strike prices and time.', url: 'https://www.fidelity.com/learning-center/investment-products/options/options-greeks' },
        { icon: 'tool', title: 'CBOE: Options Calculator', desc: 'Free tool to calculate theoretical option prices and Greeks for any stock.', url: 'https://www.cboe.com/education/tools/options-calculator/' }
      ]}
    ],
    quiz: [
      { question: 'If an option has a Delta of 0.75, what does that mean?', options: ['The option will expire in 75 days', 'The option moves 75 cents for every $1 the stock moves', 'The option costs 75% of the stock price', 'The option has a 75% chance of profit'], correct: 1, explanation: 'Delta of 0.75 means the option price moves $0.75 for every $1.00 the stock price moves \u2014 it tracks at 75% of the stock\'s speed.' },
      { question: 'What happens to option prices when volatility (Vega) increases?', options: ['Option prices decrease', 'Option prices stay the same', 'Option prices increase', 'Only put options are affected'], correct: 2, explanation: 'Higher volatility increases option premiums. When Vega is high, options cost more because there\'s greater potential for large price swings.' },
      { question: 'Theta always works against which type of options trader?', options: ['Option sellers', 'Option buyers', 'Both equally', 'Neither \u2014 Theta has no effect'], correct: 1, explanation: 'Theta (time decay) works against option BUYERS \u2014 their options lose value every day. It works IN FAVOR of option sellers who collect premium.' },
      { question: 'A call option with Stock = $120 and Strike = $100 is considered:', options: ['Out of the Money (OTM)', 'At the Money (ATM)', 'In the Money (ITM)', 'Expired'], correct: 2, explanation: 'A call is In the Money when the stock price ($120) is ABOVE the strike price ($100) \u2014 the option has $20 of intrinsic value.' },
      { question: 'Approximately how much value does a 4-month option lose to time decay?', options: ['About 5%', 'About 15%', 'About 50%', 'About 75%'], correct: 1, explanation: 'A rough rule of thumb is that a 4-month option loses approximately 15% of its value to time decay as expiration approaches.' }
    ]
  },
  {
    id: 'm15',
    title: 'Advanced Options: Leverage, Time Decay & Contingency Orders',
    subtitle: 'Master options leverage, learn why stop losses fail on options, and build a complete trading plan with contingency exits.',
    sections: [
      { title: 'Leverage Through Options', content: 'Options give you control over more shares with less money. This is the core leverage advantage that makes options one of the most powerful vehicles for traders with smaller accounts.\n\nExample with $20,000 capital:\n\u2022 Stock price: $799 per share\n\u2022 If you buy stock directly: $20,000 \u00f7 $799 \u2248 25 shares\n\u2022 With options: 1 contract controls 100 shares for a fraction of the cost\n\u2022 Your $20,000 could control several hundred shares through option contracts\n\nThis means your capital has dramatically more buying power through options. A 10% move in the stock could translate to a 50%\u2013100%+ move in your option position.\n\nBut leverage is a double-edged sword. The same force that amplifies gains also amplifies losses. This is why risk management \u2014 the 1% rule, the S.E.T. rule \u2014 is non-negotiable when trading options. Leverage without discipline is a fast path to account destruction.', type: 'text' },
      { title: 'Leverage Comparison: $20,000 Capital', type: 'stats', stats: [
        { num: '25', lbl: 'Shares Buying Stock at $799' },
        { num: '100+', lbl: 'Shares Controlled via Options' },
        { num: '4\u00d7\u201310\u00d7', lbl: 'Typical Options Leverage' },
        { num: '1%', lbl: 'Max Risk Per Trade (Always)' }
      ]},
      { title: 'Time Decay Deep Dive', content: 'Time decay (Theta) is the most misunderstood and underestimated force in options trading. Here\'s what you need to internalize:\n\nA 4-month option typically loses around 15% of its value simply because time passes \u2014 even if the stock price doesn\'t move at all. This loss happens automatically, every single day.\n\nThe time decay curve is NOT linear. It accelerates:\n\u2022 Months 4\u20133: Slow decay, barely noticeable\n\u2022 Months 3\u20132: Moderate decay, starting to feel it\n\u2022 Month 2\u20131: Noticeable acceleration\n\u2022 Last 30 days: Aggressive decay \u2014 this is where most option value evaporates\n\u2022 Last week: Extremely rapid decay\n\nAt the Money options suffer the worst time decay because they have the highest proportion of time value (extrinsic value) and zero intrinsic value. In the Money options decay more slowly because a larger portion of their price is intrinsic value, which doesn\'t decay.\n\nThis is why experienced traders often buy options with 60\u201390+ days until expiration \u2014 it gives the trade time to work while avoiding the worst acceleration of Theta.', type: 'text' },
      { title: 'Why You Need a Trading Plan', content: 'Trading without a plan exposes you to unnecessary risk. A plan removes emotion from the equation and gives you a systematic framework for every trade.\n\nYour trading plan must include these elements:\n\n1. Entry Price \u2014 The exact price where you will enter the trade. This should be pre-determined based on your analysis, not decided in the moment.\n\n2. Exit Price \u2014 Your profit target. Where will you take gains? The S.E.T. rule says your target should be 3\u00d7 your risk (3:1 reward-to-risk ratio).\n\n3. Risk Limit / Max Loss \u2014 The maximum you\'re willing to lose. Never more than 1% of your total account on any single trade.\n\n4. Profit Target(s) \u2014 Can be single or scaled (take partial profits at different levels).\n\n5. Rules for When NOT to Trade \u2014 Equally important. Define the conditions where you sit on your hands: low volume days, major news events, unclear trends, emotional states.\n\nGeneral Rule: Always protect your money using planned exits and risk management. The plan is decided BEFORE you enter. If you\'re making decisions after you\'re in the trade, you\'ve already lost control.', type: 'text' },
      { title: 'Trading Plan Checklist', type: 'stats', stats: [
        { num: '\u2713', lbl: 'Entry Price Defined' },
        { num: '\u2713', lbl: 'Exit / Profit Target Set' },
        { num: '\u2713', lbl: 'Stop Level (Max 1% Risk)' },
        { num: '\u2713', lbl: 'Position Size Calculated' },
        { num: '\u2713', lbl: 'Market Conditions Assessed' }
      ]},
      { title: '"Never Waste a Good Crisis"', content: 'Market volatility creates opportunity. When most traders panic, disciplined traders see setups forming.\n\nDuring a market crisis:\n\u2022 Option premiums expand dramatically (Vega spikes)\n\u2022 Price swings get larger and more frequent\n\u2022 Leverage becomes more powerful because options move faster\n\u2022 Supply and demand zones become more pronounced\n\nCrisis = increased volatility = more ways to profit IF you are disciplined.\n\nThe key word is "if." Volatility creates opportunity for traders who have a plan, follow their rules, and manage risk. For traders without discipline, the same volatility creates rapid account destruction. This is where the Chasm of Fear separates the top 5% from everyone else.\n\nThe traders who profit from crises are the ones who prepared during calm markets \u2014 they have their watchlists ready, their risk parameters set, and their trading plans written before the volatility arrives.', type: 'text' },
      { title: 'Stop Losses vs. Contingency Orders on Options', content: 'CRITICAL RULE: Never put a standard stop loss on an option.\n\nWhy standard stop losses fail on options:\n\u2022 Option prices whipsaw \u2014 they can drop sharply due to time decay or temporary volatility changes without the stock actually moving significantly\n\u2022 A normal stop loss triggers based on the option\'s price, which means you get kicked out of positions prematurely\n\u2022 You lose money unnecessarily because the stock was fine \u2014 it was the option\'s temporary pricing that triggered your exit\n\nThe solution: Use a Contingency Order instead.\n\nA contingency order lets you exit your option position based on the STOCK price, not the option price. This is a fundamental distinction that separates professional options traders from amateurs.\n\nContingency order examples:\n\u2022 "Sell my call option if the stock drops to $95" (stock-based trigger)\n\u2022 "Exit the position if the stock rises above $110" (profit protection)\n\u2022 "Close the contract if the stock breaks below the support level at $88" (technical trigger)\n\nBy basing your exit on the stock\'s movement \u2014 which is more stable and predictable \u2014 you avoid being shaken out by temporary option price fluctuations. The stock drives the option\'s value; control the trade based on the underlying driver, not the derivative.', type: 'text' },
      { title: 'Stop Loss vs. Contingency Order', type: 'table', headers: ['Feature', 'Standard Stop Loss', 'Contingency Order'], rows: [
        ['Trigger Based On', 'Option price', 'Stock price'],
        ['Whipsaw Risk', 'HIGH \u2014 options fluctuate wildly', 'LOW \u2014 stocks move more smoothly'],
        ['Premature Exits', 'Very common', 'Rare'],
        ['Professional Usage', 'Rarely used on options', 'Industry standard'],
        ['Control Level', 'Reactive, imprecise', 'Strategic, deliberate']
      ]},
      { title: 'Module Summary \u2014 Quick Reference', content: 'Delta = Direction and Speed \u2014 Measures how fast the option moves compared to the stock. Higher Delta means bigger moves and higher cost.\n\nVega = Volatility and Option Cost \u2014 Measures sensitivity to volatility changes. High Vega means more expensive options but more opportunity.\n\nTheta = Time Decay \u2014 Measures how much value the option loses over time. Time decay hurts option buyers and helps option sellers.\n\nATM = Strike price approximately equals stock price.\nITM = Option already has intrinsic value based on stock movement.\n\nLeverage = Control more shares with less money through options contracts.\n\nRules to Remember:\n\u2022 Always have a trading plan BEFORE entering\n\u2022 Never risk more than 1% per trade\n\u2022 Never use standard stop losses on options\n\u2022 Use contingency orders tied to stock price\n\u2022 Crisis = opportunity for disciplined traders\n\u2022 Time decay accelerates \u2014 buy enough time for the trade to work', type: 'text' },
      { title: 'Visual Resources', type: 'resources', resources: [
        { icon: 'learn', title: 'Fidelity: LEAPS and Bounds \u2014 Long-Term Options', desc: 'Guide to using long-dated options to reduce time decay impact and maximize leverage.', url: 'https://www.fidelity.com/viewpoints/active-investor/leaps-and-bounds' },
        { icon: 'tool', title: 'FOREX.com: Risk vs Reward Calculator', desc: 'Interactive tool for calculating proper risk-to-reward ratios on any trade.', url: 'https://www.forex.com/en-us/trading-academy/courses/risk-management/' },
        { icon: 'chart', title: 'TradesViz: Stop Loss & Profit Target Simulator', desc: 'Visual simulator showing how different exit strategies affect trading performance.', url: 'https://www.tradesviz.com/blog/stop-loss-profit-target-trade-simulator/' }
      ]}
    ],
    quiz: [
      { question: 'With $20,000 and a stock at $799/share, how many shares can you buy outright?', options: ['10 shares', '25 shares', '50 shares', '100 shares'], correct: 1, explanation: '$20,000 \u00f7 $799 \u2248 25 shares. With options, the same $20,000 could control several hundred shares through leverage.' },
      { question: 'Why should you NEVER put a standard stop loss on an option?', options: ['Because brokers don\'t allow it', 'Because option prices whipsaw and you get kicked out prematurely', 'Because stop losses only work on futures', 'Because options never lose value'], correct: 1, explanation: 'Option prices can drop sharply from time decay or volatility changes without the stock moving. A standard stop loss triggers on the option price and kicks you out unnecessarily.' },
      { question: 'What triggers a contingency order?', options: ['The option\'s price hitting a specific level', 'A specific date and time', 'The STOCK\'s price hitting a specific level', 'The trading volume exceeding a threshold'], correct: 2, explanation: 'Contingency orders trigger based on the STOCK price, not the option price. This avoids premature exits caused by temporary option price fluctuations.' },
      { question: 'During a market crisis, what happens to option premiums?', options: ['They shrink because nobody wants options', 'They stay the same', 'They expand dramatically due to increased volatility', 'They become free'], correct: 2, explanation: 'Market crises spike volatility (Vega), which causes option premiums to expand dramatically \u2014 creating both larger opportunities and larger risks.' },
      { question: 'What is the recommended minimum time until expiration when buying options?', options: ['1\u20132 weeks', '30 days', '60\u201390+ days', '1 year minimum'], correct: 2, explanation: 'Experienced traders typically buy options with 60\u201390+ days until expiration to give the trade time to work while avoiding the worst acceleration of time decay in the last 30 days.' }
    ]
  }
